### ISSUE TITLE
About us page, in the "why subsalve" section:

### ISSUE THREAD

**Issue by jtuckertw** [Tallwave/PIC-Subsalve#1]
Can we center the last, odd-numbered item titled "Compliand and Warranty"?

https://drive.google.com/file/d/195fxyYUvALvADf0KueUDCfvo6xW-3a0f/view?usp=sharing

**Comment by cmoosman1** [comment]
@jtuckertw - This is resolved in the current build

**Comment by jtuckertw** [comment]
Fixed - Closed
