### ISSUE TITLE
Two Picture Carousel needed for Inflatatank

### ISSUE THREAD

**Issue by jtuckertw** [Tallwave/PIC-Subsalve#102]

**Comment by cmoosman1** [comment]
@jtuckertw - We have to have 3 images for the carousel

**Comment by jtuckertw** [comment]
@TheNewWallace Michael, until we have a third image can you just duplicate one of the existing images for the empty slot?

**Comment by TheNewWallace** [comment]
i have added a third photo for inflat-a-tank
