### ISSUE TITLE
One Photo for Pipe Pluggers is very dark

### ISSUE THREAD

**Issue by jtuckertw** [Tallwave/PIC-Subsalve#103]
Is there a better image for this available?

**Comment by TheNewWallace** [comment]
to get a better picture we will need new treatment from @jthiel16

**Comment by jthiel16** [comment]
@cmoosman1 @jtuckertw Here is an updated image that's been lightened: 

[https://drive.google.com/file/d/1WGMazgL6q8w7D1Nd3n_f7J60PSFJad6q/view?usp=sharing](url)

**Comment by kylielujan** [comment]
@jtuckertw done and ready for QA
