### ISSUE TITLE
Application Details Pages - General Questions

### ISSUE THREAD

**Issue by jtuckertw** [Tallwave/PIC-Subsalve#104]
Applications Details Pages General comments

- [ ] Should cards have hover treatments?
- [ ] Should entire card be clickable? (more than just “See more details”)?
- [ ] Should cards be alpha ordered?

**Comment by jthiel16** [comment]
@jtuckertw I would say yes to all 3 questions.

For the card hover state, I recommend having it fill to color #111929 (instead of being empty).

**Comment by cmoosman1** [comment]
@jtuckertw - This is resolved in the current build

**Comment by jtuckertw** [comment]
Fixed - Closed
