### ISSUE TITLE
Home Page: Product Cards: Liquid Containment Link

### ISSUE THREAD

**Issue by jtuckertw** [Tallwave/PIC-Subsalve#107]
Needs to be linked to the AEF Site.  (Old/new)

**Comment by jtuckertw** [comment]
http://aefenvprod.wpengine.com/

**Comment by aguillen1** [comment]
@jtuckertw This card won't let me link out to the AEF website. I'm not sure how to add it

**Comment by jtuckertw** [comment]
@victorjaquez @cmoosman1 Please provide assistance for this issue.  We need the link to direct to Subsalve's page:  http://aefenvprod.wpengine.com/water-storage

**Comment by jtuckertw** [comment]
This will be resolved at go-live since it is one unpublished site pointing to another.

**Comment by jtuckertw** [comment]
close
