### ISSUE TITLE
Contact Us page:

### ISSUE THREAD

**Issue by jtuckertw** [Tallwave/PIC-Subsalve#11]
Buttons are using blue text, and need their styling updated to match previous QA issue re: hover states

https://drive.google.com/file/d/18MTqgPxtTxNkY_3IkUcbtl18iaIRsR3M/view?usp=sharing

Here is a reference for hover states:
zpl.io/2E1Ge6y

**Comment by cmoosman1** [comment]
@jtuckertw - This is resolved in the current build

**Comment by jtuckertw** [comment]
@jthiel16 Please validate and close if all is good - thanks!

**Comment by jthiel16** [comment]
The Get Directions button still needs updating, but this is mentioned in comments in issue #47, so I 'll close this one.
