### ISSUE TITLE
Homepage: News: Article Dates show 5 digits.

### ISSUE THREAD

**Issue by jtuckertw** [Tallwave/PIC-Subsalve#110]
n/t

**Comment by cmoosman1** [comment]
@jtuckertw - This is resolved in the current build

**Comment by jtuckertw** [comment]
Retest Failed: Articles now show single numbers after them "1", "2", "3" etc.

![image](https://user-images.githubusercontent.com/45019034/68270568-d9b6b180-001a-11ea-9efd-7821e527b47e.png)

**Comment by jtuckertw** [comment]
Fixed - Closed!
