### ISSUE TITLE
Add GTM tags to site

### ISSUE THREAD

**Issue by jtuckertw** [Tallwave/PIC-Subsalve#114]
Paste this code as high in the <head> of the page as possible:

<script>(function(w,d,s,l,i){w[l]=w[l]||[];w[l].push({'gtm.start':
new Date().getTime(),event:'gtm.js'});var f=d.getElementsByTagName(s)[0],
j=d.createElement(s),dl=l!='dataLayer'?'&l='+l:'';j.async=true;j.src=
'https://www.googletagmanager.com/gtm.js?id='+i+dl;f.parentNode.insertBefore(j,f);
})(window,document,'script','dataLayer','GTM-5JB2JZQ');</script>

Additionally, paste this code immediately after the opening <body> tag:

<noscript><iframe src="https://www.googletagmanager.com/ns.html?id=GTM-5JB2JZQ"
height="0" width="0" style="display:none;visibility:hidden"></iframe></noscript>

**Comment by cmoosman1** [comment]
@jtuckertw - This is resolved in the current build

**Comment by jtuckertw** [comment]
Reported to Krystina.

**Comment by jtuckertw** [comment]
Fixed - Closed
