### ISSUE TITLE
Navigations are messed up in Header on Non-Homepage Pages

### ISSUE THREAD

**Issue by jtuckertw** [Tallwave/PIC-Subsalve#115]
3/17 Update Problem seems to be confined to Edge

Steps to Reproduce:
1) Navigate to Accessories
2) Click Case Studies in the header menu
3) Result: It leads to Accessories

**Comment by cmoosman1** [comment]
@jtuckertw - This is resolved in the current build

**Comment by jtuckertw** [comment]
Still out there - clarified the steps to recreate.

**Comment by cmoosman1** [comment]
@jtuckertw - This is resolved in the current build

**Comment by jtuckertw** [comment]
Resolved

**Comment by jtuckertw** [comment]
https://drive.google.com/open?id=1QpmJEIJGM5SiJkpBAVZ9LqJWU3xZ2_xX

**Comment by jtuckertw** [comment]
Seems resolved now.
