### ISSUE TITLE
Calendar:  Hoolie Con and DOD Underwater Expo links lead to wrong Calendar dates

### ISSUE THREAD

**Issue by jtuckertw** [Tallwave/PIC-Subsalve#117]
Steps to Reproduce:
1) Navigate to Homepage
2) Scroll to Events
3) Click on HoolieCon or DOD event and see results in calendar are different than dates on homepage

Unsure whose issue this is - Dev or Content

**Comment by cmoosman1** [comment]
@jtuckertw - This is resolved in the current build
