### ISSUE TITLE
Client Concern: Multiple rows of same product

### ISSUE THREAD

**Issue by jtuckertw** [Tallwave/PIC-Subsalve#119]
Client dislikes the metric and english units being represented on two rows.  Is there a different treatment that will allow the data to be consolidated on a single row?

**Comment by TheNewWallace** [comment]
table functionality is limited and if we place both metric and imperial in the same row search engine understanding of the data will be hampered.

**Comment by britnigallello** [comment]
@jtuckertw I don't think this is something that can be addressed with the current design. I tried to play around with it myself, but need to be cognizant of Mike's comment above. Let me know how you'd like me to proceed.

**Comment by jtuckertw** [comment]
@britnigallello Your second opinion was perfect - will work with the client to figure out how to make this limitation acceptable.

**Comment by jtuckertw** [comment]
@cmoosman1 Worked with client to come up with a solution for this.  He is not happy that the same product is represented on two different rows.
Would be happier if either of the following accommodations could be made
1) A button that would allow users to flip back and forth between English and Metric units (seems like a heavy lift)
2) A way to configure the shading so that the English Units and Metric Units Show as same color for same product.  Currently the shading alternates making it appear that the same product is different (seems like this could be an easier lift)

![image](https://user-images.githubusercontent.com/45019034/71568912-3a48f480-2a88-11ea-890c-b580bdb32c3e.png)

**Comment by cmoosman1** [comment]
@jtuckertw - This is way out of scope and a huge lift, we would have to completely rework the table component we are using if not change it all together.

**Comment by jtuckertw** [comment]
Please modify ALL products in the same format as the one shown below, separating out the English Units from the Metric units, ensuring that the product in one table is shaded as the same in the next table.  i.e. if CS200 is Blue in the english table it needs to be blue in the metric table.  This will require us to add or delete lines between the tables.

http://subsalve.wpengine.com/enclosed-shallow-water-flotation-bags/

**Comment by aguillen1** [comment]
@zuzannaczerny

**Comment by aguillen1** [comment]
@jtuckertw This table for pipe pluggers is only in inches and feet. Should I leave it as is or do the math?: http://subsalve.wpengine.com/pipe-pluggers

**Comment by jtuckertw** [comment]
Pipe Pluggers is only in English units.  We are good to go on that table - thanks for asking!  @aguillen1  

https://docs.google.com/spreadsheets/d/1PzHKZ6jR9APVuwbpyVhKs4NxDefh8qjgErKj-IemT1Y/edit#gid=1253443869

**Comment by aguillen1** [comment]
@jtuckertw All product tables should be good to go! Let me know if you see anything that needs updating!

**Comment by jtuckertw** [comment]
@Aguillen1 and zuzanna!  TYVM!  Jeff to check in detail much later...
