### ISSUE TITLE
Client Issue: Product Detail Pages - Descriptions - Lift Straps

### ISSUE THREAD

**Issue by jtuckertw** [Tallwave/PIC-Subsalve#121]
Client says this might be a client provided content issue:  Lift Straps are referred to inconsistently within each product, differing by product. Sometimes it is a safety feature, other times it is not, etc.

**Comment by TheNewWallace** [comment]
this is going to be a content issue that would fall under retainer work post launch or additional hours under a T&M contract

**Comment by britnigallello** [comment]
@jtuckertw is this critical for launch or can we fix this post-launch? Please confirm.

**Comment by jtuckertw** [comment]
@britnigallello Post - Launch - thank you for the note!
