### ISSUE TITLE
Product Detail: Mark V/Orca

### ISSUE THREAD

**Issue by jtuckertw** [Tallwave/PIC-Subsalve#127]
Items shown on Page 11 of Catalog need to be shown as accessories for the Mark V

http://subsalve.com/wp-content/uploads/2015/01/Subsalve-Catalog-PDF.pdf

**Comment by TheNewWallace** [comment]
confused on this one. which photos am i moving and where am i moving them?

**Comment by jtuckertw** [comment]
Optional Accessories detail needed from Client

**Comment by jtuckertw** [comment]
Each of the items on Page 11 of the catalog need to be cropped, labeled and shown as accessories for the Mark V/Orca Product.

**Comment by aguillen1** [comment]
@jtuckertw This terrible image has been added: http://subsalve.wpengine.com/mark-v-orca

**Comment by jtuckertw** [comment]
@aguillen1  Accessories need to be shown in accessories at bottom of page.  Please remove from Mark V images at top.

**Comment by aguillen1** [comment]
@jtuckertw This image has been removed and the accessory has been added below on the backend – it hasn't shown up for me, but it's in the backend! http://subsalve.wpengine.com/mark-v-orca

**Comment by jtuckertw** [comment]
@aguillen1 @cmoosman1 - Please work together on this one.

Hmmm Opt Acoustic Actuation System and Opt Quad Kit still showing in Product Hero carousel, products not replicating in Accessory area.

**Comment by aguillen1** [comment]
@jtuckertw Ready for QA http://subsalve.wpengine.com/mark-v-orca

**Comment by jtuckertw** [comment]
Perfect @aguillen1 Thank you!
