### ISSUE TITLE
Applications detail pages (ie, http://subsalve.wpengine.com/pipeline-and-tunnel):

### ISSUE THREAD

**Issue by jtuckertw** [Tallwave/PIC-Subsalve#13]
In this example the 3 cards are spread out, close to centered but not quite.

Can we set these cards up so that they're always centered within the browser, no matter if there's 1, 2, 3 or 4 across?

https://drive.google.com/file/d/18KqNwCl4NfL9xIVQyzz-iJeQfKxIm7LI/view?usp=sharing

https://drive.google.com/file/d/18EWcqw8ynreJAs0f2xaHLNQFEiqcd4Bq/view?usp=sharing

https://drive.google.com/file/d/18C_sucYe0WFJl1v_ux3vwVEZFjht2sI3/view?usp=sharing

**Comment by cmoosman1** [comment]
@jtuckertw - This is resolved in the current build

**Comment by jtuckertw** [comment]
@jthiel16 Please validate and close if all looks good - thanks!

**Comment by jthiel16** [comment]
Looks good, thank you
