### ISSUE TITLE
Case Studies: Featured Case Study

### ISSUE THREAD

**Issue by jtuckertw** [Tallwave/PIC-Subsalve#130]
@TheNewWallace Featured Case Study is not one of the four case studies

**Comment by TheNewWallace** [comment]
im confused on this one. the featured case study is the james cameron case study

**Comment by britnigallello** [comment]
@jtuckertw can you provide some clarity on this one for me please?

**Comment by jtuckertw** [comment]
@britnigallello Sure - Navigate to Case Studies Page, where Featured case study is shown as "Dubai Voluntary Diving Team",  This is neither a case study nor our featured one.  Should be the James Cameron one.

**Comment by cmoosman1** [comment]
@jtuckertw - This is resolved in the current build

**Comment by jtuckertw** [comment]
Perfect!
