### ISSUE TITLE
Case Studies: Divider Line and View Case Study Buttons- Horizontal Alignment

### ISSUE THREAD

**Issue by jtuckertw** [Tallwave/PIC-Subsalve#131]
Case Studies: Divider Line and View Case Study Buttons should be Horizontal Alignment.  Currently they are each at staggered positions on the cards.

**Comment by cmoosman1** [comment]
@jtuckertw - Per my conversation with @jthiel16 he preferred the buttons be pinned to the bottom of the container and the rest of the content within the card flow and fill the space.

**Comment by jtuckertw** [comment]
@jthiel Please re-validate and close if good.  Thanks!

**Comment by jthiel16** [comment]
@jtuckertw @cmoosman1 I like how the buttons are bottom-aligned now, **but would like for the images to all be the same height**. This should fix some of the mis-alignment that's happening:

<img width="1177" alt="Screen Shot 2019-11-12 at 9 54 39 AM" src="https://user-images.githubusercontent.com/35710312/68692471-cf247c80-0532-11ea-92e9-c9031c1c8a1d.png">
<img width="1193" alt="Screen Shot 2019-11-12 at 9 54 44 AM" src="https://user-images.githubusercontent.com/35710312/68692472-cf247c80-0532-11ea-8239-63bace337e1d.png">

**Comment by jtuckertw** [comment]
Fixed
