### ISSUE TITLE
Case Studies: Each card shows "Applications"

### ISSUE THREAD

**Issue by jtuckertw** [Tallwave/PIC-Subsalve#133]
Is this correct?  Applications seems like a strange intro to each case study card.  Please advise.

**Comment by jthiel16** [comment]
@jtuckertw The intention there was to list out the associated Applications underneath that heading, for each case study card, like this: 

https://drive.google.com/file/d/1TXCjQN_4czK5ZLKWO-KJb99ByuLbO5hf/view?usp=sharing

**Comment by jtuckertw** [comment]
@britnigallello Applications need to be loaded from case study tab of the PIC Content Spreadsheet
https://docs.google.com/spreadsheets/d/1PzHKZ6jR9APVuwbpyVhKs4NxDefh8qjgErKj-IemT1Y/edit#gid=0

**Comment by cmoosman1** [comment]
@jtuckertw - This is resolved in the current build

**Comment by jtuckertw** [comment]
Resolved
