### ISSUE TITLE
Case Studies Page: Case Study Cards

### ISSUE THREAD

**Issue by jtuckertw** [Tallwave/PIC-Subsalve#134]
Four case studies do not belong here:
Dubai Voluntary Diving Team
Bolivian Navy
TSIRI 
Academy of Malaysia

Two Case Studies are missing cards:
Group Ocean
James Cameron

**Comment by TheNewWallace** [comment]
this is a dev issue for @cmoosman1

**Comment by cmoosman1** [comment]
Group Ocean
James Cameron
Costa Norte
Kokoshing 
Remove all other case studies

**Comment by cmoosman1** [comment]
@jtuckertw - This is resolved in the current build

**Comment by cmoosman1** [comment]
@jtuckertw - This is resolved in the current build

**Comment by jtuckertw** [comment]
Perfect!
