### ISSUE TITLE
Case Study: Costa Norte 

### ISSUE THREAD

**Issue by jtuckertw** [Tallwave/PIC-Subsalve#135]
Navigate to Case Study Detail page (any of them):
- [ ] Tile boxes covering text - This is not appearing all the time and is likely context specific.
PC, Chrome, 1366x768
![image](https://user-images.githubusercontent.com/45019034/71044898-387a4b00-20f0-11ea-84d8-f233707703e4.png)

- [x] Bottom left image is too big

**Comment by TheNewWallace** [comment]
reassigned to @cmoosman1

**Comment by cmoosman1** [comment]
@jtuckertw - This is resolved in the current build

**Comment by jtuckertw** [comment]
@jtucker to retest on smaller resolution.  Could only confirm that image size has been corrected.

**Comment by jtuckertw** [comment]
Other three issues still remain.

**Comment by jtuckertw** [comment]
Fixed
