### ISSUE TITLE
Case Study Detail Pages: All Pages show images from Cameron rather than specific case studies

### ISSUE THREAD

**Issue by jtuckertw** [Tallwave/PIC-Subsalve#136]

**Comment by TheNewWallace** [comment]
this is the "featured case study" feature being added underneath each case study in order to fill in the page. if this needs to be removed it would be @cmoosman1

**Comment by britnigallello** [comment]
@cmoosman1 can you confirm whether or not that needs to be removed?

**Comment by jtuckertw** [comment]
@britnigallello I'm pretty sure this is more of a content than a dev issue.  Each case study has its own photos, (located here: https://docs.google.com/spreadsheets/d/1PzHKZ6jR9APVuwbpyVhKs4NxDefh8qjgErKj-IemT1Y/edit#gid=927461111 Case Study tab)  but it seems that all of the case studies were built with the cameron images rather than the specified images linked in the Content sheet.  ooo but I see where it could be a dev issue, especially if there is no actual content block to load images for the individual case studies on the page....

**Comment by aguillen1** [comment]
@jtuckertw All case study cards now have the corresponding imagery. Please let me know if you see one I might've missed!

**Comment by jtuckertw** [comment]
@aguillen TYVM! Jeff to review in detail later.

**Comment by jtuckertw** [comment]
@victorjaquez Kokosing case study is broken again.  http://subsalve.wpengine.com/kokosing-industrial

**Comment by jtuckertw** [comment]
@jthiel6 Jason would you be able to correct-size the image on http://subsalve.wpengine.com/kokosing-industrial please?

**Comment by jthiel16** [comment]
@jtuckertw @victorjaquez I think it would be better if the images auto-fit to the specific container height (by cropping the sides if neccessary). That way, in the future as they add more or swap out imagery it wouldn't break the layout. I'm seeing the same issue on other Case Study pages. @victorjaquez Is that something we can do?

Also could we remove the "Image Switch" text and icon from the large images? There's no action for the user to take from there, so it's misleading to keep is visible.
<img width="811" alt="Screen Shot 2020-03-11 at 11 06 17 AM" src="https://user-images.githubusercontent.com/35710312/76451120-2d038c80-638c-11ea-8288-f765e80afc06.png">

**Comment by cmoosman1** [comment]
@jtuckertw - Are you wanting to remove the click functionality or just the over state on the large image?

**Comment by jthiel16** [comment]
@cmoosman1 Just the over state on the large image

**Comment by cmoosman1** [comment]
@jtuckertw - The overlay and click functionality have been removed

**Comment by jtuckertw** [comment]
Fixed, thank you @cmoosman1
