### ISSUE TITLE
Case Studies Detail Pages: Text Truncation in Challenge, Solution, Outcome

### ISSUE THREAD

**Issue by jtuckertw** [Tallwave/PIC-Subsalve#137]
Text is truncated in numerous spots:

Costa Norte: Solution
James Cameron: Challenge, Solution
Kokosing: Solution

**Comment by TheNewWallace** [comment]
yeah this is all @cmoosman1. I already placed in the appropriate text

**Comment by cmoosman1** [comment]
@jtuckertw - Text is truncated need a design solution?

**Comment by jtuckertw** [comment]
@jthiel16 Can you provide a design solution for this issue?

**Comment by jthiel16** [comment]
@jtuckertw Do we know how much text is getting cut off? As long as it's not a ridiculous length of copy, I'd recommend extending the height of each of the 3 boxes to accommodate. 

@cmoosman1 can these be set up so they auto-adjust to the height of the text entered within the container (while keeping the height of all 3 containers the same as each other)?

**Comment by jtuckertw** [comment]
Text is no longer cut off.  James Cameron boxes nearly touch images below, but I think this is now passable.  Closing.
