### ISSUE TITLE
About Us: 1985 Ordnance spelled incorrectly

### ISSUE THREAD

**Issue by jtuckertw** [Tallwave/PIC-Subsalve#139]

**Comment by TheNewWallace** [comment]
fixed

**Comment by britnigallello** [comment]
@jtuckertw this was marked resolved, and I just QA'ed - it's spelled correctly. Not to be confused with the word ORDINANCE,  ORDNANCE is the correct spelling for this. If there is somewhere I am missing this, please provide a screenshot.

**Comment by jtuckertw** [comment]
I took MW off of all defects and assigned them to you this morning.  I didn't realize this one had been closed - will move it to the DONE column - thank you!

PS I'm a spelling freak...spotting all instances of ordnance on the site.
@britnigallello
