### ISSUE TITLE
Product detail page: Show 3 case studies at all times?

### ISSUE THREAD

**Issue by jtuckertw** [Tallwave/PIC-Subsalve#14]
Content question/issue: in the "Subsalve Case Studies" global component, I think we should always show 3, as long as we have enough. Will that work or is there a reason we're only showing 2 here?

https://drive.google.com/file/d/18CZO0oeZoHnsSqBIaGnqwXfI-PlATfHt/view?usp=sharing

**Comment by cmoosman1** [comment]
@jtuckertw - Those are associated with the products, Im guessing @TheNewWallace only associated two?

**Comment by jtuckertw** [comment]
Agreed - Let's let client decide

**Comment by jtuckertw** [comment]
The number is dependent on the number of case studies associated with the product.
