### ISSUE TITLE
About Us: 2018

### ISSUE THREAD

**Issue by jtuckertw** [Tallwave/PIC-Subsalve#141]
2018 Logo photo on right hand side seems weird - It is not a complete logo.

**Comment by TheNewWallace** [comment]
i was told to pass this ticket to @jthiel16

**Comment by jthiel16** [comment]
@jtuckertw @cmoosman1 I can correct this with an image update if given login creds

**Comment by cmoosman1** [comment]
@jthiel16 - You should get an em with access to WP admin to resolve this.

**Comment by jthiel16** [comment]
Images are updated
