### ISSUE TITLE
News Card Links

### ISSUE THREAD

**Issue by jtuckertw** [Tallwave/PIC-Subsalve#143]
Almost all news card links leads to a new non-PIC website.  In cases where the user is navigated to a nonPIC page, a new window should open with that content.  The current behavior increases bounce rates and adversely impacts SEO

**Comment by cmoosman1** [comment]
@jtuckertw - This is resolved in the current build

**Comment by jtuckertw** [comment]
Content still opens in same window.  New window (or tab) should open

**Comment by cmoosman1** [comment]
@jtuckertw - This is resolved in the current build

**Comment by jtuckertw** [comment]
@cmoosman1 Content still opens in same window. New window (or tab) should open

**Comment by jtuckertw** [comment]
Fixed
