### ISSUE TITLE
Contact Us Page Shows AEF Info

### ISSUE THREAD

**Issue by jtuckertw** [Tallwave/PIC-Subsalve#144]
All of the information ere should be for Subsalve, not AEF

See content spreadsheet for correct email address: sales@...

**Comment by TheNewWallace** [comment]
no field on the page that I am able to edit in order to change this. might be a template change for @cmoosman1

**Comment by cmoosman1** [comment]
@jtuckertw - This is resolved in the current build

**Comment by jtuckertw** [comment]
Email should be sales@subsalve.com

**Comment by cmoosman1** [comment]
@jtuckertw - This is resolved in the current build

**Comment by jtuckertw** [comment]
Perfect! closed
