### ISSUE TITLE
Case Study Text Blocks are obscuring the titles

### ISSUE THREAD

**Issue by jtuckertw** [Tallwave/PIC-Subsalve#145]
Note - this does not happen on large monitors - only on smaller laptop screens.

![image](https://user-images.githubusercontent.com/45019034/68612892-ccfee700-047a-11ea-9e22-29a24506d427.png)

**Comment by jtuckertw** [comment]
@cmoosman1 let's walk through this on mobile and desktop.  PC, Chrome, All Case study pages

**Comment by jtuckertw** [comment]
Bug Still Occurs in normal viewing size on smaller screens::
Steps to recreate if using a larger monitor.
Navigate to any case study page.  
Use controls to shrink page to smaller size and the image shown above will be replicated.  This is the normal view for smaller monitor sizes.

**Comment by cmoosman1** [comment]
@jtuckertw - I have resolved this for user resizing of browser.

**Comment by jtuckertw** [comment]
Issue is still occurring @cmoosman1  
![image](https://user-images.githubusercontent.com/45019034/72270076-d541e280-35e1-11ea-961b-38517ba3ee1e.png)

**Comment by jtuckertw** [comment]
Looks awesome @cmoosman1.  Please provide code to @victorjaquez for this - we are having this issue on AEF.
