### ISSUE TITLE
Favicon is not a transparent image

### ISSUE THREAD

**Issue by jthiel16** [Tallwave/PIC-Subsalve#146]
The favicon is showing white corners around the icon's circular shape. 
This should be a transparent png, without the corners

[https://drive.google.com/file/d/1W-5Ye5KMY1Eu_KU7USXINoJAqPomYzcM/view?usp=sharing](url)

**Comment by cmoosman1** [comment]
@jthiel16 - The favicon is a png if you can send me a different version of it I will upload it.

**Comment by jthiel16** [comment]
Thanks @cmoosman1 Favicons can be found in Zeplin, or here: 
![subsalve-logo-favicon-32-x-32](https://user-images.githubusercontent.com/35710312/71920176-6ed14600-3143-11ea-8105-4c5767fd2aee.png)

**Comment by jthiel16** [comment]
Looks good, thanks ... closing ticket
