### ISSUE TITLE
Home Page – Case Studies Hover

### ISSUE THREAD

**Issue by jthiel16** [Tallwave/PIC-Subsalve#148]
In the Case Studies  section of the home page, the large image has a hover state that says "Image Switch", but it doesn't do anything.

I suggest we remove that hover state from the large image, and just keep it for the little ones.

<img width="1230" alt="Screen Shot 2019-11-12 at 11 43 33 AM" src="https://user-images.githubusercontent.com/35710312/68700227-bd96a100-0541-11ea-8475-eac171644c41.png">

**Comment by jtuckertw** [comment]
Resolved - Image switch now works.
