### ISSUE TITLE
Oceans Five Case Study

### ISSUE THREAD

**Issue by jtuckertw** [Tallwave/PIC-Subsalve#149]
Need to determine if we add this to scope or refer to next SOW.  Consult with Kylie.

Kylie Approved for work under existing scope.

**Comment by britnigallello** [comment]
@jtuckertw according to Kylie, this case study is done. Dev just needs to add it to the site

**Comment by kylielujan** [comment]
@victorjaquez here is what we have for content https://drive.google.com/drive/folders/1MdCn3d4jLvWn-fWQUeskgVht8gLYGMKI

Thanks!

**Comment by aguillen1** [comment]
@jtuckertw This page has been updated, but was in draft mode in the backend. Also are we referring to it as Oceans Five or Ocean5? I'm seeing results for both in Google as well as how Subsalve labeled things within the Google Drive

**Comment by jtuckertw** [comment]
Oceans 5 @aguillen1 TY!

**Comment by aguillen1** [comment]
@jtuckertw This case study and its card has been uploaded in the backend. @cmoosman1 was looking into why it wasn't populating: http://subsalve.wpengine.com/oceans-5

**Comment by cmoosman1** [comment]
This is resolved

**Comment by jtuckertw** [comment]
FIXED
