### ISSUE TITLE
Aircraft Lift Bag Ground Cover Photo Delivered

### ISSUE THREAD

**Issue by jtuckertw** [Tallwave/PIC-Subsalve#150]
Accessory for the ACLB page.
Photo here: https://drive.google.com/drive/folders/1tSvghS5FBCU81xnww4KifJPB9DI4OIzT
Description: Rolled up Ground Cover

**Comment by kylielujan** [comment]
@jtuckertw to clarify, do I need to add this to the accessories page first and then link to the ACLB page?

**Comment by aguillen1** [comment]
@jtuckertw This image has been added: http://subsalve.wpengine.com/aircraft-lift-bags/

**Comment by jtuckertw** [comment]
@aguillen1 please remove from header area.  Add as an accessory to the bottom of the page.

**Comment by aguillen1** [comment]
@jtuckertw This change has been made in the backend: http://subsalve.wpengine.com/aircraft-lift-bags

**Comment by jtuckertw** [comment]
Awesome!  @aguillen1 TYVM!
