### ISSUE TITLE
Research Hero Photo Delivered

### ISSUE THREAD

**Issue by jtuckertw** [Tallwave/PIC-Subsalve#151]
Client would like this Hero photo to be used instead of current for the Research Application:
https://drive.google.com/drive/folders/19OMAviwVW5LkEv_vKQjwIedIpcRn6zys

**Comment by kylielujan** [comment]
@jtuckertw this link pulls up four images. Which one does the client want?

**Comment by jtuckertw** [comment]
@kylielujan The one that says "Research Hero" please

**Comment by kylielujan** [comment]
Ready for QA
