### ISSUE TITLE
Registered/TM Logo needed on homepage

### ISSUE THREAD

**Issue by jtuckertw** [Tallwave/PIC-Subsalve#155]
@jthiel16  can you supply the image for @cmoosman1 to load, please? 

![image](https://user-images.githubusercontent.com/45019034/71044190-3b743c00-20ee-11ea-9d33-447a5d04cddb.png)

**Comment by jthiel16** [comment]
@cmoosman1 @jtuckertw Here is the registered version:

[https://drive.google.com/file/d/1fqXNUIaxTC4_szHjneDxlnuXJJPFesIh/view?usp=sharing](url)

**Comment by jtuckertw** [comment]
Pass - wow that is tiny!

**Comment by jtuckertw** [comment]
Sending to @jthiel16  for second opinion.  The mark almost looks like a period at this size.  Recommendation?

**Comment by jthiel16** [comment]
@jtuckertw Here's an updated logo with larger ®. This should work better

[https://drive.google.com/file/d/18eUQSSCECXlWJ-f8Kdt44yq_8sfgewr0/view?usp=sharing](url)

![subsalve-logo-no-tag-horizontal-RGB-®@2x](https://user-images.githubusercontent.com/35710312/73687851-1af54680-4688-11ea-8e5e-4ba760cdbf43.png)

**Comment by jtuckertw** [comment]
THanks @jthiel16 !   @aguillen1  would you be able to replace this image, please?

**Comment by aguillen1** [comment]
@jtuckertw I updated the logo, but it looks the same 🤷🏽‍♀️ http://subsalve.wpengine.com/

**Comment by jthiel16** [comment]
@aguillen1 @jtuckertw I wonder if Criss needs to do a push in order for us to see the change?

I agree, that still looks like the old version. In the new one, the ® is the same height as the tail of the "E"

**Comment by jtuckertw** [comment]
@aguillen @cmoosman1 Logo Image is not the correct image.

**Comment by aguillen1** [comment]
@jtuckertw This looks good on my end now: http://subsalve.wpengine.com/

**Comment by jtuckertw** [comment]
Fixed
