### ISSUE TITLE
Shipyard Draft Reduction Application Issues

### ISSUE THREAD

**Issue by jtuckertw** [Tallwave/PIC-Subsalve#158]
http://subsalve.wpengine.com/shipyard-draft-reduction

- [x] Title needs to be reverted to Shipyard & Draft Reduction
- [x] Commercial Liftbags should be removed 
- [x] Salvage Pontoons should be inserted
- [x] Lifeboat Davit Test kits should be inserted

**Comment by kylielujan** [comment]
@jtuckertw I've updated the tags. Should be ready for review.

**Comment by jtuckertw** [comment]
THe one that says "Research Hero" please.

**Comment by aguillen1** [comment]
@jtuckertw This page is ready for QA: http://subsalve.wpengine.com/shipyard-draft-reduction

**Comment by jtuckertw** [comment]
Issue on Megamenu @aguillen @cmoosman1 

![image](https://user-images.githubusercontent.com/45019034/74908498-34c6a700-5373-11ea-953c-f27bebd5779b.png)

**Comment by jtuckertw** [comment]
Fixed
