### ISSUE TITLE
Product details page, Accessories section (ie, http://subsalve.wpengine.com/aircraft-lift-bags):

### ISSUE THREAD

**Issue by jtuckertw** [Tallwave/PIC-Subsalve#16]
When accessories section only has 1, 2 or 3 cards listed, can we center them inside the container, like the "Accessories" heading does.

https://drive.google.com/file/d/187SR1ttb0WI9RJ8ranRA5wYOqUxgAf18/view?usp=sharing

https://drive.google.com/file/d/184LyygQGpyenGPkf7LAQfpRIAB9aaH5s/view?usp=sharing

**Comment by cmoosman1** [comment]
@jtuckertw - This is resolved in the current build

**Comment by jtuckertw** [comment]
Fixed - Closed
