### ISSUE TITLE
Client Identified: Initial Load of site will sometimes hang on the Mobile view

### ISSUE THREAD

**Issue by jtuckertw** [Tallwave/PIC-Subsalve#160]
Navigate to: http://subsalve.wpengine.com/

See Hamburger menu instead of Nav Menu
![image](https://user-images.githubusercontent.com/45019034/73148952-23dc8b80-407c-11ea-80e5-c6ea2f6019d3.png)

**Comment by cmoosman1** [comment]
@jtuckertw - This will have an initial flash of the mobile header as it pulls the navigation in. Because of the way react-snap is handling static rendering we can't get around this. I was able to minimize but it still will happen occasionally.

**Comment by jtuckertw** [comment]
Thank you for the update @cmoosman1.  Closing issue.
