### ISSUE TITLE
Complete Catalog not loaded

### ISSUE THREAD

**Issue by jtuckertw** [Tallwave/PIC-Subsalve#161]
Pages 22-24 got stripped from the current site.,

Full doc can be found here:
http://subsalve.com/wp-content/uploads/2015/01/Subsalve-Catalog-PDF.pdf

**Comment by cmoosman1** [comment]
@jtuckertw - We need a full version of the catalog, once you have that you can upload it and set everything in the WP admin.

**Comment by cmoosman1** [comment]
@jtuckertw - Do you have a full version of the catalog?

**Comment by jtuckertw** [comment]
Ugh I thought I posted it above and it apparently did not load.  THe full version is out on the SUbsalve site.  

![image](https://user-images.githubusercontent.com/45019034/73672320-e377a180-4669-11ea-82a3-67af0eb8a929.png)

**Comment by jtuckertw** [comment]
Thank you! @cmoosman1!
