### ISSUE TITLE
Using Back arrow from Product Detail page to Products page leads to broken page

### ISSUE THREAD

**Issue by jtuckertw** [Tallwave/PIC-Subsalve#163]
Steps to recreate:
Navigate to Product Page
Click Professional Lift Bag Card
Use back arrow to get to Product Page

Result:  Page is completely broken.
![image](https://user-images.githubusercontent.com/45019034/73151494-9f443a00-4088-11ea-8c9d-b39da0ba410e.png)

![image](https://user-images.githubusercontent.com/45019034/73151535-d0bd0580-4088-11ea-9b2b-4e2a5deee365.png)

**Comment by victorjaquez** [comment]
@jtuckertw this is fixed

**Comment by jtuckertw** [comment]
This does not seem fixed yet.  Now what appears to be happening is the page loads for a half second and then reverts to the blank images shown above.

**Comment by jtuckertw** [comment]
Possible missing content.  Criss to research

**Comment by jtuckertw** [comment]
FIXED
