### ISSUE TITLE
Kokosing Images are wrong

### ISSUE THREAD

**Issue by jtuckertw** [Tallwave/PIC-Subsalve#165]
https://drive.google.com/open?id=1ZpdCpUc_1SV5EAwEpoXWu7EQ4P0aQaSj

**Comment by aguillen1** [comment]
@jtuckertw Kokosing imagery is in the backend, but the case study page is being weird: http://subsalve.wpengine.com/kokosing-industrial/

**Comment by jtuckertw** [comment]
@cmoosman1 Entire Page is hosed

**Comment by jtuckertw** [comment]
Alejandra to post 3 images even if one is a duplicate.

**Comment by aguillen1** [comment]
@jtuckertw There are 3 images in the backend now, but the page still isn't showing up for me: http://subsalve.wpengine.com/kokosing-industrial

**Comment by jtuckertw** [comment]
@cmoosman1 Page is wonky.

![image](https://user-images.githubusercontent.com/45019034/75319488-0260f200-582a-11ea-936c-2abfd3252de3.png)

**Comment by jtuckertw** [comment]
Hi, @cmoosman1. My walkthrough with Subsalve is tomorrow (2/27).  Any chance of this one getting fixed?

**Comment by jtuckertw** [comment]
FIXED
