### ISSUE TITLE
About Us: Hero Image

### ISSUE THREAD

**Issue by jtuckertw** [Tallwave/PIC-Subsalve#166]
Cameron Image needed instead of current image.

**Comment by jtuckertw** [comment]
Use any cool photos associated with this case study

https://drive.google.com/drive/folders/1EyngM8mh6Vw9kaCc5Y7mlkbfjXMIhLvv

**Comment by aguillen1** [comment]
@jtuckertw Added new hero image. Ready for QA: http://subsalve.wpengine.com/about-us/

**Comment by jtuckertw** [comment]
@aguillen Hero image is still the same as it was before.  This is not a cameron image from this folder: https://drive.google.com/drive/folders/1EyngM8mh6Vw9kaCc5Y7mlkbfjXMIhLvv.

**Comment by aguillen1** [comment]
@jtuckertw The image change is reflected in the backend, but the images provided by the client are all small (670 x 447 px). @cmoosman1 Could the size be the reason why the hero image isn't populating? http://subsalve.wpengine.com/about-us/

**Comment by jtuckertw** [comment]
FIXED
