### ISSUE TITLE
Case Studies section is empty on About Us

### ISSUE THREAD

**Issue by jtuckertw** [Tallwave/PIC-Subsalve#167]
![image](https://user-images.githubusercontent.com/45019034/73152572-a6ba1200-408d-11ea-9d10-ac4223031785.png)

**Comment by victorjaquez** [comment]
@cmoosman1 in Template B
<img width="795" alt="Screen Shot 2020-01-31 at 11 56 02 AM" src="https://user-images.githubusercontent.com/20385537/73566308-cd2ad500-4420-11ea-9498-13a38593bff5.png">

**Comment by jtuckertw** [comment]
Fixed!
