### ISSUE TITLE
Hall Of Fame News Item

### ISSUE THREAD

**Issue by jtuckertw** [Tallwave/PIC-Subsalve#168]
https://drive.google.com/drive/folders/14cBFm03EwQNv4wqgi0llQfhfjzQZI3qM

Rich to send additional content

**Comment by aguillen1** [comment]
@jtuckertw Added to News section! Ready for QA: http://subsalvestage.wpengine.com/

**Comment by jtuckertw** [comment]
@aguillen1  I think you might be working on the wrong server.  http://subsalve.wpengine.com/ is the correct server.  Also did the news item publish?  I do not see it on the link you pointed me to.  

![image](https://user-images.githubusercontent.com/45019034/74673527-94069a80-516c-11ea-94cc-9ca786f39c5a.png)


Ping me if we need to chat more about this.

**Comment by aguillen1** [comment]
@jtuckertw Talking to Criss about this – All of my changes are reflected in the backend. It may be a coding issue.

**Comment by aguillen1** [comment]
@jtuckertw This has been updated! http://subsalve.wpengine.com/

**Comment by jtuckertw** [comment]
Added.
