### ISSUE TITLE
Further Application Detail to be implemented Tab 1

### ISSUE THREAD

**Issue by jtuckertw** [Tallwave/PIC-Subsalve#169]
https://drive.google.com/drive/folders/102XwlaBCkeUdrbbr-3U0FwZVlRiPul-1

Review both tabs

**Comment by aguillen1** [comment]
@jtuckertw All applications have the added detail: http://subsalve.wpengine.com/aircraft-and-vehicle-recovery

**Comment by jtuckertw** [comment]
@aguillen1 Tab 2 was missed. Opened new issue to cover those items.
