### ISSUE TITLE
Product details pages, in the "Product Detail" accordion section:

### ISSUE THREAD

**Issue by jtuckertw** [Tallwave/PIC-Subsalve#17]
We are missing the "wave" background pattern

**Comment by cmoosman1** [comment]
@jtuckertw - There is no background pattern in the mockup its a solid color

**Comment by jthiel16** [comment]
@cmoosman1 It's subtle, but it's there: https://invis.io/N6UD9H6ATX9

**Comment by cmoosman1** [comment]
@jtuckertw - This is resolved in the current build

**Comment by jthiel16** [comment]
@cmoosman1 the pattern should be the blue version (like the one used behind the "Trusted By" logos section on the home page. 

Right now it's using a gray version

**Comment by jtuckertw** [comment]
Fixed
