### ISSUE TITLE
Product Pages Updates per Rich's Spreadsheet Tab 2

### ISSUE THREAD

**Issue by jtuckertw** [Tallwave/PIC-Subsalve#173]
Source: https://docs.google.com/spreadsheets/d/0B6ZQMsMmAFJLYUEyZUF6bm5kSVBEdXFzX2lvLXVlMHdyNjFF/edit#gid=1600411138

- [x] Our Products Header description:  

Subsalve has an extensive range of standard products.  If you do not see a product that suits your application please contact us. Subsalve is a leader in delivering custom solutions

**For the Products Pages Rich wants to have more consistency between the product description categories using Fabric, Safety and Ease-of-Use Features, Multiple Applications, Subsalve Promise,
Product Specifications whenever possible**

- [x] ACLB  Move optional Sizes and Dims after Prod Specs

- [x] BRS  Add fabric section, Relabel "What's Included" text

- [x] Cable and Pipeline - Replace current description, Add Fabric section,  -add note see Enclosed Flotation Bags and Salvage Pontoons for larger projects, Show Kokosing case study

- [x] Enclosed Flotation Bags - Merge Lifting Harness into Safety box. Multiple Applications - Adaptive ??? not sure what that means.

- [x]  Shallow Water Flotation Bag Remove caution picture from header images, add to end of Product Specifications

- [x] Inflat-a-tank - Add Accessories - accessory Major repari kit, 3/4 " camloc, Stainless steel ball valve.  Not sure we have last two accs loaded.

- [x] Lifeboats - Add Fabric Section, Relabel Product Components as "Safety and Ease-of-Use Features", Include Major Repair Kit acc, Remove Flex strap from carousel at the top

- [x] Mark V - Add Fabric section, Merge Usage Details and Included Accessories into single "Safety and Ease-of-Use" Section.  Add pictures of Optional and Included accessories in Accesories section.

- [x] Pipe Pluggers - Change "Features" to Safety and Ease-of-Use Features

- [x] Professional Enclosed Lift Bags: Relabel "Features and Design" as "Multiple Applications", Move Multiple Applications section after Easy to Use.

- [x] Propeller Bag - show minor repair kit as accessory

- [x] Quad Bag - Relabel Product Features to "Safety and Ease-of-Use Features",Relabel "Uses" Section as "Multiple Applications", Move Multiple Applications to follow Safety and  Ease-of-Use

- [x] RRS - Add Fabric section, Revise "Features" to "Safety and Ease-of-Use Features", 

- [x] Salvage Pontoons - Relabel "Fittings" to "Safety and Ease-of-Use Features", add Lifting Beam as an accessory (Not sure that we have photo)

- [x] Salvage Pontoons - Vertical -  Revise Fittings to "Safety and Ease-of-Use Features", 

- [x] Vehicle Recovery Systems - Merge Usage and System Components into a single "Safety and Ease-Of-Use Features" section,   ReUse photo shown in VRS in Public Safety

- [x] Water Load Test Bag - Relabel Lift Strap to "Safety and Ease-OF-Use Features" , add the camlock accessory (not sure we have this)

**Comment by aguillen1** [comment]
@jtuckertw

- ACLB: Optional Products and Dimensions can't be moved after Product Specs on my end. They are two separate entities.

- BRS: No information provided on what to include in the "Fabric Section," so I copied and pasted from the ACLB Fabric section. Doesn't seem right. Changed "What's Included" section to "Ease-of-Use" features"

- Cable and Pipeline: Changes have been made. Ready for QA  http://subsalve.wpengine.com/cable-floats

- Enclosed Flotation: Just added a bullet with "multiple applications" to the Adaptive tab in the accordion. Ready for QA http://subsalve.wpengine.com/enclosed-flotation-bags

- Shallow Water Flotation Bag: Removed image but can't add to the end of Product Specifications. Please let me know how to proceed: http://subsalve.wpengine.com/enclosed-shallow-water-flotation-bags

- Inflat-A-Tank: Accessories have been added: http://subsalve.wpengine.com/inflat-a-tank

- Lifeboats: Ready for QA: http://subsalve.wpengine.com/lifeboat-davit-test-bags

- Mark V Orca: Changes have been made. Not all accessories listed live on website. Ready for QA: http://subsalve.wpengine.com/mark-v-orca

- Pipe pluggers: Ready for QA http://subsalve.wpengine.com/pipe-pluggers

- Professional Enclosed Lift Bags: Ready for QA http://subsalve.wpengine.com/professional-enclosed-lift-bags

- Propeller bags: Ready for QA http://subsalve.wpengine.com/propeller-bags

- Quad Bag: Ready for QA http://subsalve.wpengine.com/quad-bags

- RRS: Ready for QA http://subsalve.wpengine.com/rapid-recovery-systems

- Salvage pontoons: We don't have lifting beam as an accessory on the website. Ready for QA: http://subsalve.wpengine.com/rapid-recovery-systems

- Salvage pontoons.- vertical: Ready for QA http://subsalve.wpengine.com/salvage-pontoons-vertical

- Vehicle recovery systems: Content has been merged. Ready for QA http://subsalve.wpengine.com/vehicle-recovery-systems
Added photo to Public Safety: http://subsalve.wpengine.com/public-safety

- Water Load Test Bags: Ready for QA http://subsalve.wpengine.com/water-load-testing-bags

**Comment by jtuckertw** [comment]
@aguillen1  Thank you for conquering this beast!  Yay! Additional tasks are below...Boo!

- [x] ACLB 1)Jeff to assign to cmoosman for section move/relabel. 
- [x] ACLB 2)Description missing - @aguillen1 
- [x] BRS - Great copy workaround @aguillen1! Need to update to "Safety and Ease-of-Use Features"
- [x] CPL Note needs to be added per spreadsheet @aguillen1 
- [x] CLB - Jeff missed from spreadsheet - create new ticket
- [x] EFB - This one got way mangled in instructions, sorry. Jeff to create new ticket:  Copy Lifting Harness copy box text to Safety and Ease of Use..", Add New "Multiple Applications" Box,  Copy Adaptive text to "Mult App" box. Delete Adaptive Box, Delete Lifting Harness box
- [x] Shallow - If images cannot be placed in the accordion then we should delete the image altogether. @aguillen1 
Inflat-A-Tank - Awesome! 
- [x] Lifeboats - Product Hero - Eliminate third image or duplicate another image please. @aguillen1 
- [ ] Mark V - 1) Jeff to id which accessories are missing, 
- [x] Mark V - 2) @aguillen1 Please remove accessories from Header and place in accessories section(I think this might be a duplicate request from a diff ticket)
PPLug - Awesome!
PELB - Awesome!
Prop Bag - Awesome!
Quad Bag - Awesome!
RRS - Awesome!
- [ ] SP - Awesome @aguillen1  Jeff to request lifting beam photo
SPV - Awesome!
VRS - Double Awesome! @aguillen1 
WLTB - Awesome!

**Comment by aguillen1** [comment]
@jtuckertw No need for a separate task – I think I got everything I could today do on this task. Ready for another round of QA!

**Comment by jtuckertw** [comment]
Nice!!  Just two items left, @aguillen1 

- [x] ACLB -  In description at top, after U.S. Air Force replace existing text with …and many commercial and military customers around the world.  <Keep the NSN notation.>
BRS - Perfect
CPL - Perfect
CLB - Perfect- thank you!
EFB - Perfect - Double thank you!
Shallow - Perfect
Lifeboats - Perfect (for now, anyway)
Mark V super cool  
- [x] Mark V is there a way to resize these so all accessories are consistent?
- [ ] Jeff to request lifting beam photo for Salvage Pontoons

**Comment by aguillen1** [comment]
@jtuckertw ACLB description should also be updated. As for the Mark V, I took that Actuation Valve screenshot from the catalog and it was the smallest photo of all time. I can't get it any bigger or in a square shape without also capturing the rest of the items on that page. If they have another photo, they can send it over!

**Comment by jtuckertw** [comment]
All items fixed and Closed.  Lifting beam currently outstanding by client
