### ISSUE TITLE
Trusted by Titan is old logo.  Replace with Ardent

### ISSUE THREAD

**Issue by jtuckertw** [Tallwave/PIC-Subsalve#176]
Jason can you pull a new logo for "Ardent" please?  Apparently the one we used as "Titan" is now outdated.

**Comment by jthiel16** [comment]
@jtuckertw No problem, the new Ardent logo is here: 
[https://drive.google.com/file/d/1LkxllN20vGmIOx2xsOKflNC_s6PEL1Tz/view?usp=sharing](url)

![client-logo-ardent@2x](https://user-images.githubusercontent.com/35710312/75268285-8d9fa080-57b4-11ea-8fec-b33ef5382ffa.png)

**Comment by jtuckertw** [comment]
@jthiel - thank you!  ATTN: @aguillen1, one more change please.

**Comment by aguillen1** [comment]
@jtuckertw Ardent logo has been added in the backend: http://subsalve.wpengine.com/

**Comment by jtuckertw** [comment]
Looks awesome TY @aguillen1 and @jthiel16 !
