### ISSUE TITLE
Please load newest calendar

### ISSUE THREAD

**Issue by jtuckertw** [Tallwave/PIC-Subsalve#177]
https://drive.google.com/open?id=1DLHuAtPupOuRB9QTn4LaE6_c8DJqrlbg

**Comment by aguillen1** [comment]
@jtuckertw New event has been added to Subsalve calendar. I will add to AEF tomorrow: http://subsalve.wpengine.com/

**Comment by jtuckertw** [comment]
Thank you so much @aguillen1 !
