### ISSUE TITLE
Cable/Pipeline Table Product Specifications Exception

### ISSUE THREAD

**Issue by jtuckertw** [Tallwave/PIC-Subsalve#178]
cable/pipeline table is currently EFB-SW, but instead should show BOTH SFB tables first, and then SP tables. Standard and Metric shall be noted for each table and divided out.

Table source: https://docs.google.com/spreadsheets/d/1PzHKZ6jR9APVuwbpyVhKs4NxDefh8qjgErKj-IemT1Y/edit#gid=1253443869

Order of Tables
SFB Standard (Cable Float/Pipeline Float Tables)
SFB Metric
SP Standard (Salvage Pontoon Tables)
SP Metric

**Comment by aguillen1** [comment]
@jtuckertw Ready for QA http://subsalve.wpengine.com/cable-floats

**Comment by jtuckertw** [comment]
Thank you @aguillen1
