### ISSUE TITLE
Product details page, in the "Product Detail" accordion (ie, http://subsalve.wpengine.com/aircraft-lift-bags):

### ISSUE THREAD

**Issue by jtuckertw** [Tallwave/PIC-Subsalve#18]
The "plus" and "minus" icons aren't functioning as expected ...

After opening one of the accordions, the blue "minus" icon appears within the table, while keeping the "plus" icon in view also.

Expected behavior: After clicking plus, the minus icon should replace it, in the same spot

https://drive.google.com/file/d/184CMB2MfJ3IVykd3cWqHP1mAsAl1FO7N/view?usp=sharing

**Comment by cmoosman1** [comment]
@jtuckertw - This is resolved in the current build

**Comment by jtuckertw** [comment]
This is still messed up:
Requirements: 
1) + should only appear when any area is closed
2) - should only appear when any section is opened
3) The controls should work independently of each other.

The + appears sometimes when things are open: violating rule 1
 
![image](https://user-images.githubusercontent.com/45019034/68718853-be422e00-0567-11ea-8714-8c5f1c6d76b7.png)

The minus appears sometimes when things are closed violating rule 2 (button 1 makes this behavior happen)
![image](https://user-images.githubusercontent.com/45019034/68719165-8e475a80-0568-11ea-8ede-912802ca6b19.png)

The top and bottom buttons control the state of the other buttons, violating rule number 3
![image](https://user-images.githubusercontent.com/45019034/68718901-dd40c000-0567-11ea-82ee-3b416cd3461c.png)

**Comment by cmoosman1** [comment]
@jtuckertw  - This is a duplicate closing
