### ISSUE TITLE
"More" Case Studies does not make sense on Application Pages

### ISSUE THREAD

**Issue by jtuckertw** [Tallwave/PIC-Subsalve#182]
All applications have the Case Studies section titles MORE Case Studies.  Remove "More" text from all Application pages, Should be Subsalve Case Studies, as on the product pages.

This may be a dev issue due to the same block being re-used in both places.

**Comment by aguillen1** [comment]
@jtuckertw I'm not seeing a section to make this change on my end – This will likely have to go to dev

**Comment by jtuckertw** [comment]
Did not check all - Fixed based on random sample
