### ISSUE TITLE
Text on Large Photo Block of Featured case Study (Homepage) does not provide enough context

### ISSUE THREAD

**Issue by jtuckertw** [Tallwave/PIC-Subsalve#184]
Append Text next to large photo block 
"When James Cameron made his record setting dive to the bottom of the Mariana Trench Subsalve provided…"  resume text
Examine other case studies Determine if similar edits needed elsewhere in case studies.

**Comment by aguillen1** [comment]
@jtuckertw Updated content: http://subsalve.wpengine.com/
