### ISSUE TITLE
Text next to Featured Case Study (homepage) photo blocks needs more context

### ISSUE THREAD

**Issue by jtuckertw** [Tallwave/PIC-Subsalve#185]
Append Text next to large photo block for Cameron with the following
"When James Cameron made his record setting dive to the bottom of the Mariana Trench Subsalve provided…"
Determine if similar edits needed for all other case studies.

**Comment by aguillen1** [comment]
@jtuckertw This change has been made: http://subsalve.wpengine.com/

**Comment by jtuckertw** [comment]
Thank you @aguillen1!
