### ISSUE TITLE
About Us - New 2020 Diving Hall of Fame Dot Needed on Timeline

### ISSUE THREAD

**Issue by jtuckertw** [Tallwave/PIC-Subsalve#186]
- [x] @victorjaquez  Timeline add new dot 2020 Inducted into Commercial Diving Hall of Fame. Add picture.

- [x] @Aguillen1 See News story for text

- [x] @aguillen1 See link for image https://drive.google.com/drive/folders/14cBFm03EwQNv4wqgi0llQfhfjzQZI3qM

- [x] @aguillen Hall of Fame news story was added to home page but not showing up on news page.

**Comment by aguillen1** [comment]
@jtuckertw Hall of Fame has been added to news page: http://subsalve.wpengine.com/news
and timeline: http://subsalve.wpengine.com/about-us

**Comment by jtuckertw** [comment]
- [ ] @victorjaquez Timeline line needs to connect 2018 and 2020.  
- [x] @aguillen1 Subsalve Diving Related pic needed for right hand side of page.

**Comment by aguillen1** [comment]
@jtuckertw  Diving image is in the backend

**Comment by jtuckertw** [comment]
@victorjaquez when you get a moment there is still a small graphical issue - the timeline line needs to connect 2018 and 2020.

**Comment by jtuckertw** [comment]
Fixed.  Thank you @cmoosman1
