### ISSUE TITLE
Main Nav: Applications "See All Applications"

### ISSUE THREAD

**Issue by jtuckertw** [Tallwave/PIC-Subsalve#188]
There is no "See All Applications"  in the Nav menu - client would like consistency,

Although there is no page for applications I suggested that we could look into making this a link to the home page with an anchor that drops the user to the Products section of the page.

Note: This link exists in the Mobile view, but is broken

**Comment by cmoosman1** [comment]
@jtuckertw - This is a considerable level of effort to do an anchor tag in a React SPA application. This isnt a standard HTML a href. everything in react runs through a router that controls the navigation flow. We can simulate an anchor tag but it takes alot of extra code/testing as we will need to add onClick handlers and scrollTo handlers to manage this. LOE is around 4-6 hr dev with a couple hr of testing.

**Comment by jtuckertw** [comment]
close
