### ISSUE TITLE
New Accessories cards need to be sized correctly

### ISSUE THREAD

**Issue by jtuckertw** [Tallwave/PIC-Subsalve#189]
Jason, Alejandra did the best she could with the crappy images that we had available.  Would you be able to size the three new images better, so they are at least h- and v-aligned with the other images on the page?

http://subsalve.wpengine.com/accessories

**Comment by jthiel16** [comment]
No problem! @aguillen1 here are updated images for those first 4:
[https://drive.google.com/drive/folders/1Ukp_VlbpkbRJ_mKPbNTh6v8K0WuQapMM?usp=sharing](url)

![subsalve-01-optional-quad-kit@2x](https://user-images.githubusercontent.com/35710312/76259693-6cf33400-6213-11ea-892d-79b0950d01c3.jpg)
![subsalve-02-optional-acoustic-actuation-system@2x](https://user-images.githubusercontent.com/35710312/76259698-6e246100-6213-11ea-8ecc-22a9a07a7691.jpg)
![subsalve-03-rolled-up-ground-cover@2x](https://user-images.githubusercontent.com/35710312/76259700-6ebcf780-6213-11ea-9f0a-0cc12df1ddf5.jpg)
![subsalve-04-actuation-valve@2x](https://user-images.githubusercontent.com/35710312/76259701-6f558e00-6213-11ea-98e2-134943b68fd7.jpg)

**Comment by aguillen1** [comment]
@jtuckertw The accessory images have been updated: http://subsalve.wpengine.com/

**Comment by jtuckertw** [comment]
Perfect!  Thank you @jthiel16 !
