### ISSUE TITLE
Product details page, in the "Product Detail" accordion (http://subsalve.wpengine.com/aircraft-lift-bags):

### ISSUE THREAD

**Issue by jtuckertw** [Tallwave/PIC-Subsalve#19]
• Same issue as the section above it ... there is a lot of extra space after the end of the accordion, and the start of the next section. Can we make this div auto-adjust the height, based on however many items are in the accordion?

• The content/headings and the plus icons are not centered vertically within the container

• Rounded corners are showing up between each of the accordion sections. I think we should just square those off

https://drive.google.com/file/d/180N8czCw5Ia1f8ooMW98C7miNLkLjbIi/view?usp=sharing

**Comment by cmoosman1** [comment]
@jtuckertw - This is resolved in the current build

**Comment by jtuckertw** [comment]
@jthiel16 Please re-validate and close if all is good. Thanks!

**Comment by jthiel16** [comment]
@cmoosman1 @jtuckertw First issue is resolved, but I'm still seeing the 2nd and 3rd bullets

• The content/headings and the plus icons are not centered vertically within the container

• Rounded corners are showing up between each of the accordion sections. I think we should just square those off

**Comment by jtuckertw** [comment]
Fixxed
