### ISSUE TITLE
Enclosed Shallow Water Flotation Bags Photo

### ISSUE THREAD

**Issue by jtuckertw** [Tallwave/PIC-Subsalve#192]
https://drive.google.com/open?id=1I_ZYZjkVHgoEprAxZZT4StfoGX80Wm7L

Must be placed on the page....however....where and how?  Ugh,

**Comment by aguillen1** [comment]
@jtuckertw The photo has been embedded into the accordion: http://subsalve.wpengine.com/enclosed-shallow-water-flotation-bags

**Comment by jtuckertw** [comment]
Looks awesome - tyvm @aguillen1
