### ISSUE TITLE
Data Table Cleanups

### ISSUE THREAD

**Issue by jtuckertw** [Tallwave/PIC-Subsalve#193]
- [x] Aircraft Lift Bags - Data is incorrect
- [ ] Bomb Recovery System - Data is incorrect
- [x] Commercial Lift Bags - Data is incorrect
- [x] Vehicle Recovery Systems - Data is incorrect
- [x] PFE - Correct Data, but headings are incorrect
- [ ] PF - Correct Data, but headings are incorrect
- [x] Propeller Bags - Correct Data, but headings are incorrect

The headings must show Standard and Metric only on white lines.   
Standard and Metric must be in bold font.

**Comment by aguillen1** [comment]
@jtuckertw The headings for these tables were taken directly from the spreadsheet provided from the client. Zuzanna is working on updating anything with incorrect data.

**Comment by jtuckertw** [comment]
Thank you both for your work on this.  @zuzannaczerny @aguillen1 

Whoever gets to it first, please remove the other from the assignee list, please

- [x] Bomb Recovery System.  Move data that is in Safety and Ease of Use to Product Specifications.
- [x] Bomb Recovery System. Eliminate all table data in Product Specifications
- [x] Bomb Recovery System. Eliminate Safety and Ease of Use Feature section
- [x]  Professional Enclosed Flotation Bags - Correct Data, but headings are incorrect - Include Row for "Standard" Heading
- [x]  Professional Flotation Bags - Correct Data, but headings are incorrect- Include Row for "Standard" Heading
- [x]  Propeller Bags - Correct Data, but headings are incorrect- Include Row for "Standard" Heading

**Comment by zuzannaczerny** [comment]
Updated, @jtuckertw can you please take a look when you have the chance. Thanks!

**Comment by jtuckertw** [comment]
Thanks @zuzannaczerny Just a couple of changes:

- [x] Bomb Recovery System should have a Product Specification section that says:
·  Specially designed for use by law enforcement to recover or remove explosives or other dangerous devices. 
·  The Bomb Recovery System 100 includes the following. 
·  One 25lb float 
·  One 50b float 
·  One 100lb float ·  
Each float includes one 2.5psi pressure relief valve and a 1/4in quick disconnect for infl ation. 
·  100ft LP inflation hose with quick disconnects 
·  105ft high strength polypro line with carabiner 
·  Carry bag

- [x] On the Professional Lift Bags Product Spec table, please insert a blank line between the PF-100000 row and the "Metric" Label.  This will make it so that the "Metric" appears on a shaded line.

Thank you!

**Comment by zuzannaczerny** [comment]
@jtuckertw updated :)
