### ISSUE TITLE
Events Edits

### ISSUE THREAD

**Issue by jtuckertw** [Tallwave/PIC-Subsalve#194]
Rich provided this updated exhibit list - we must delete the ones not shown.

https://drive.google.com/open?id=1Ib69vL-pIPsDBxFAQByzrjA8_IE935ry

**Comment by aguillen1** [comment]
@jtuckertw Events not on the list have been removed http://subsalve.wpengine.com/

**Comment by jtuckertw** [comment]
These look great - Thank you @aguillen1
