### ISSUE TITLE
Client Identified Issue: Download Button Disappears for certain screen widths.

### ISSUE THREAD

**Issue by jtuckertw** [Tallwave/PIC-Subsalve#196]
Appears on PIC and Subsalve:
1) Replication: Open http://subsalve.wpengine.com/
2) Minimize browser allowing resizing of window
3) Resize window from full screen width to hamburger menu.

The following responsive "breakpoints" will reveal missing Download Catalog buttons:

![image](https://user-images.githubusercontent.com/45019034/76559833-22fd8e80-645d-11ea-9c56-902d563a1e2b.png)

![image](https://user-images.githubusercontent.com/45019034/76559867-34469b00-645d-11ea-8096-c5cad8095127.png)

**Comment by cmoosman1** [comment]
@jtuckertw - This is by design, between 1280-960 only the menu will be present the download button takes up to much real estate at those screen resolutions.

**Comment by jtuckertw** [comment]
Missing Download button cannot be by design.  We will need to switch to hamburger menu sooner if no other solution exists.

**Comment by cmoosman1** [comment]
@jtuckertw - I have removed the main navigation and loaded the mobile nav per your instruction for med browser resolutions.

**Comment by jtuckertw** [comment]
Fixed - Resolved.
