### ISSUE TITLE
RD issue: Product Images off-center at certain screen width

### ISSUE THREAD

**Issue by jtuckertw** [Tallwave/PIC-Subsalve#197]
Issue exists on AEF and Subsalve (Subsalve example shown)
reopened.  Replication steps: Navigate to any product detail page, and shrink width slowly.

Sample Page: http://aefenvprod.wpengine.com/fuel-storage

There are three views depending upon the width.  Large Desktop, Smaller desktop, and Mobile.
The smaller desktop view shows the centering issue.

![image](https://user-images.githubusercontent.com/45019034/76561258-28100d00-6460-11ea-9686-4b7cf14c6545.png)

**Comment by cmoosman1** [comment]
@jtuckertw - Looking at this on Edge/Chrome and FF at small/med/large break points everything is centered and as expected. See screen shots
<img width="1253" alt="Screen Shot 2020-03-17 at 3 13 37 PM" src="https://user-images.githubusercontent.com/49693121/76906867-1e244a80-6862-11ea-8ba5-e8afbf2f88c5.png">
<img width="615" alt="Screen Shot 2020-03-17 at 3 11 42 PM" src="https://user-images.githubusercontent.com/49693121/76906885-28dedf80-6862-11ea-8d29-99d853c5b9cb.png">
<img width="1678" alt="Screen Shot 2020-03-17 at 3 13 57 PM" src="https://user-images.githubusercontent.com/49693121/76906893-2f6d5700-6862-11ea-8aa8-4d24c7dcb9e5.png">

**Comment by jtuckertw** [comment]
This is not working at one of the four breakpoints.  Let's walk through this together, tomorrow, please @cmoosman1 .

**Comment by cmoosman1** [comment]
@jtuckertw - How many breakpoints are we going for? sm/md/lg pretty much the standard and as you can see by the screen sots we have that covered.

**Comment by cmoosman1** [comment]
@jtuckertw - This is resolved

**Comment by jtuckertw** [comment]
Perfect - thank you @cmoosman1 !
