### ISSUE TITLE
Internet Edge: Events text issue on Home Page

### ISSUE THREAD

**Issue by jtuckertw** [Tallwave/PIC-Subsalve#198]
![image](https://user-images.githubusercontent.com/45019034/76562596-f0569480-6462-11ea-8c35-46d67c2b15d6.png)

**Comment by cmoosman1** [comment]
@jtuckertw - This is working as expected in Edge
<img width="1499" alt="Screen Shot 2020-03-17 at 5 51 39 PM" src="https://user-images.githubusercontent.com/49693121/76914581-fb9d2c00-6877-11ea-98ea-5ab5ab79249f.png">

**Comment by jtuckertw** [comment]
Let's walk through this one together tomorrow, please, @cmoosman1 .  This is not showing on my side.

**Comment by cmoosman1** [comment]
@jtuckertw - This is resolved on Edge

**Comment by jtuckertw** [comment]
Yes!  It is!  Thank you @cmoosman1
