### ISSUE TITLE
MS Edge: Main Nav Links not working

### ISSUE THREAD

**Issue by jtuckertw** [Tallwave/PIC-Subsalve#199]
News, About Us, Contact do not work in edge
Same issue exists for Subsalve

![image](https://user-images.githubusercontent.com/45019034/76576356-12f6a680-647f-11ea-80cf-046d7d21678f.png)

**Comment by cmoosman1** [comment]
@jtuckertw - This is working as expected in edge bot Victor and I have tested this.

**Comment by jtuckertw** [comment]
Let's walk through this one together tomorrow, please, @cmoosman1 .  We will clear my cache and get whatever diagnostics you need for it.

**Comment by cmoosman1** [comment]
@jtuckertw - This is resolved on Edge

**Comment by jtuckertw** [comment]
Perfect!  Thank you, @cmoosman1 !
