### ISSUE TITLE
Case Study "Under Construction" Test

### ISSUE THREAD

**Issue by jtuckertw** [Tallwave/PIC-Subsalve#200]
@aguillen1 Now that the "case study" images have been loaded/tagged, before we go through and create/publish all these, would you be able to further craft and publish a sample case study, showing them what one "Under Construction" case study detail page will look like with the "Under Construction" verbiage?  This sample case study should be added to the More Case studies section on each of the main case study pages.

Please feel free to use your creative license with this task.  Let me know if you have any questions.

**Comment by aguillen1** [comment]
@jtuckertw Updated the verbiage and published the Deco Habitat case study page. I don't know how to get this case study to appear in the menu – @cmoosman1 can you assist?

**Comment by cmoosman1** [comment]
@jtuckertw - This has been added to the navigation

**Comment by jtuckertw** [comment]
@cmoosman1 Thanks, Criss. The page is not rendering properly - however that might be due to the very limited content we have on this page.  It will be no more than the case study title, a few images, and lots of remarks stating - "Under Construction"

http://subsalve.wpengine.com/deco-habitat

Right now, in Edge though, it is showing this:
![image](https://user-images.githubusercontent.com/45019034/77267553-34fede80-6c60-11ea-8ec1-d3e3a370c79b.png)

**Comment by cmoosman1** [comment]
@jtuckertw - You have to provide something in WP or you are just going to get the template rendered wit broken. images and blank spaces were content should be.

**Comment by cmoosman1** [comment]
@jtuckertw - Technically everything is working as expected.

**Comment by jtuckertw** [comment]
@aguillen1 We may have to meet regarding this one.  I'm told the page breaks when there is not content filled in every spot.  Can you ensure "Under Construction" verbiage is repeated in every spot where content would normally go?

**Comment by aguillen1** [comment]
@jtuckertw All of the "Under Construction" verbiage is already repeated where content would normally go 🤷🏽‍♀️I added a Background Image to see if that would help as well, but it doesn't look like anything has changed on my end.

**Comment by jtuckertw** [comment]
@cmoosman1 Alejandra says everything she would normally input has been inputted into the Deco Habits Case Study but the page still does not work.  Any thoughts?

**Comment by cmoosman1** [comment]
@jtuckertw - This is resolved

**Comment by jtuckertw** [comment]
@cmoosman1 - Thank you, Criss!  Any idea why the title is not showing?
@aguillen1 - Please review the title to see if it might be a content issue.  Please revise Under Construction on the cards to "Coming Soon" or something even shorter if appropriate.

**Comment by cmoosman1** [comment]
@jtuckertw - Not sure what you are asking here? The title is showing do you not want it to show?

**Comment by jtuckertw** [comment]
Very weird @cmoosman1 I wish I had taken a screen shot - it is showing now!  Removing request!  Thanks!

**Comment by jtuckertw** [comment]
@aguillen1 Just the "Under Construction" to "Coming Soon" or something shorter, please is the only issue left
![image](https://user-images.githubusercontent.com/45019034/77684716-8efcee00-6f57-11ea-8465-08c7fbf3e93d.png)
