### ISSUE TITLE
Safari Homepage: Accessories link back to homepage

### ISSUE THREAD

**Issue by jtuckertw** [Tallwave/PIC-Subsalve#201]
Accessories on homepage should link to the Accessories page.
![image](https://user-images.githubusercontent.com/45019034/76596075-82d65280-64ba-11ea-858a-010e5da42a34.png)

**Comment by jtuckertw** [comment]
@zuzannaczerny Would you see if this is fixed?  I was unable to test due to not being able to load a current Safari browser on my PC.

**Comment by zuzannaczerny** [comment]
@jtuckertw  this has been fixed and it's good to go :)

**Comment by jtuckertw** [comment]
super! Thank you!
