### ISSUE TITLE
Safari: Homepage has horizontal scroll

### ISSUE THREAD

**Issue by jtuckertw** [Tallwave/PIC-Subsalve#202]
Able to scroll right on screen in Safari

![image](https://user-images.githubusercontent.com/45019034/76596177-b4e7b480-64ba-11ea-830e-1700c626dccf.png)

**Comment by jtuckertw** [comment]
@zuzannaczerny Would you be able to retest this?  I am unable to get a current safari browser on my PC-based machines.

**Comment by zuzannaczerny** [comment]
@jtuckertw still happens on Safari.

**Comment by cmoosman1** [comment]
@jtuckertw - This is resolved in Safari

**Comment by jtuckertw** [comment]
Thanks @cmoosman1 !
@zuzannaczerny Would you be able to retest this please?

**Comment by zuzannaczerny** [comment]
@jtuckertw this has been fixed :)

**Comment by jtuckertw** [comment]
@zuzannaczerny @cmoosman1 Thank you both!
