### ISSUE TITLE
See all Applications link does not work

### ISSUE THREAD

**Issue by jtuckertw** [Tallwave/PIC-Subsalve#205]
Remove "See All" - Thank you for trying to code this functionality

![image](https://user-images.githubusercontent.com/45019034/76596376-3d665500-64bb-11ea-9268-cc1112e6e4d4.png)

**Comment by cmoosman1** [comment]
@jtuckertw - The "see all" as been removed.

**Comment by jtuckertw** [comment]
Thank you, @cmoosman1
