### ISSUE TITLE
Safari: Christ Statue Article does not work

### ISSUE THREAD

**Issue by jtuckertw** [Tallwave/PIC-Subsalve#206]
Will ask Zuzanna to retest.

![image](https://user-images.githubusercontent.com/45019034/76596483-89b19500-64bb-11ea-8ee2-06ac11d7c84c.png)

**Comment by jtuckertw** [comment]
@zuzannaczerny I was not able to replicate this one Can you try it again, please?

**Comment by zuzannaczerny** [comment]
@jtuckertw it still doesn't work!

**Comment by cmoosman1** [comment]
@jtuckertw - The article links out to what seems to be the correct website

**Comment by jtuckertw** [comment]
@zuzannaczerny Please retest and share a video.  Thank you!

**Comment by zuzannaczerny** [comment]
@jtuckertw I was able to get it to work today! Maybe the link was broken or something, we're all good :)

**Comment by jtuckertw** [comment]
Thank you @zuzannaczerny !
