### ISSUE TITLE
Safari Mobile: Two dates on timeline are missing

### ISSUE THREAD

**Issue by jtuckertw** [Tallwave/PIC-Subsalve#207]
![image](https://user-images.githubusercontent.com/45019034/76596544-a9e15400-64bb-11ea-8d05-d10b24f06e0a.png)

**Comment by jtuckertw** [comment]
Attempted retest of Zuzanna's identified defect.  could not replicate.

**Comment by jtuckertw** [comment]
@zuzannaczerny  can you retest this and let me know if you are still experiencing this?  I tested on an iphone (Safari browser) and could not replicate it.  Thank you!

**Comment by zuzannaczerny** [comment]
@jtuckertw Yes, so the buttons and the dates do not work on desktop, please let me know if you need a video :)

**Comment by jtuckertw** [comment]
A video would be awesome please.  Thank you @zuzannaczerny

**Comment by jtuckertw** [comment]
https://drive.google.com/open?id=10ORhYu12W5vMAV2a4NJlVbJE9wUqFyyb

**Comment by cmoosman1** [comment]
@jtuckertw - This is resolved test with Safari Version 13.0.5 (15608.5.11)

**Comment by jtuckertw** [comment]
Thanks @cmoosman1!

 @zuzannaczerny please retest.

**Comment by zuzannaczerny** [comment]
@jtuckertw are the dots meant to be clickable? Once they go into a mobile mode they are no longer clickable and the dates do not appear below the dots, they appear to the left-hand side. Please let me know if this scenario is correct!

**Comment by jtuckertw** [comment]
@zuzannaczerny Yes - the dots and the years are meant to be clickable

**Comment by zuzannaczerny** [comment]
@jtuckertw okay so they are currently not clickable when it goes into ipad/mobile format.

**Comment by jtuckertw** [comment]
Thank you, @zuzannaczerny 
@cmoosman1 would you be able to address the click issues referenced above, please?

**Comment by cmoosman1** [comment]
@jtuckertw - This is resolved

**Comment by jtuckertw** [comment]
@zuzannaczerny Would you be able to retest, please?

**Comment by zuzannaczerny** [comment]
@jtuckertw the dots officially work! The date remains on the left-hand side, is that okay?

**Comment by jtuckertw** [comment]
@zuzannaczerny probably not but given that it is functional I am going to close until further notice - thank you!
