### ISSUE TITLE
Accessories Verbiage Edits

### ISSUE THREAD

**Issue by jtuckertw** [Tallwave/PIC-Subsalve#208]
Please revise the following descriptions:

- [x] Rolled up ground cover should be just "Ground Cover"
- [x] Pin Shackle should be  Screw Pin Shackle 5/8”-2”
- [x] PRV-S-HV… add “(special order)” to end of it
- [x] Ball valve should be  “SSBV-Ball valve”
- [x] Quick disconnect should be  “SSQD-Quick Disconnect”

**Comment by aguillen1** [comment]
@jtuckertw All changes have been made on the pages.

**Comment by jtuckertw** [comment]
Thank you! @aguillen1
