### ISSUE TITLE
Remaining Application Photos

### ISSUE THREAD

**Issue by jtuckertw** [Tallwave/PIC-Subsalve#210]
Please upload and label each of the following accessories.

https://drive.google.com/open?id=1DcJim5Ogbc7nckRp4BQ8mjkgQpQRCsqu

The SP-40 with Spreader is the lifting beam  Client has requested if we can annotate the image with an Arrow pointing at the beam and labeling it "Lifting Beam (SP bag not included)"

**Comment by aguillen1** [comment]
@jtuckertw Are these all new accessories that they want added to the website? I'm not seeing any descriptions to accompany them in this sheet: https://drive.google.com/drive/u/0/folders/102XwlaBCkeUdrbbr-3U0FwZVlRiPul-1

**Comment by aguillen1** [comment]
@jtuckertw Just wanted to follow up here in case you missed my comment above!

**Comment by jtuckertw** [comment]
Ugh I thought I responded to this - so sorry @aguillen1   I may not have hit post comment.  FOr these, yes, please add the photos and a description similar to the file name for the items, to the accessories pages

http://subsalve.wpengine.com/accessories

![image](https://user-images.githubusercontent.com/45019034/77374430-f16fa780-6d27-11ea-8546-15e774090aae.png)
SP-40 with Lifting Beam (SP-40 not included)
MVO Pneumatic Actuation
Carry Bag
Umbilical Sheath - Yellow
Umbilical Sheath - Red
Umbilical Sheath - Green

**Comment by aguillen1** [comment]
These accessories have been added @jtuckertw

**Comment by jtuckertw** [comment]
@aguillen1  Thank you for the image loads!
@jthiel16 When you get a moment would you be able to please resize these new images with consistency?  Also the client would like an arrow pointing to the lifting beam shown in she "SP-40 with lifting Beam".  The beam is the silver rod connected at the five points at the bottom of the image.

**Comment by jthiel16** [comment]
@jtuckertw No problem, here are the updated images:
[https://drive.google.com/drive/folders/1Xv7k--HId1s7hG4gAeb31mjTgVW72LVO?usp=sharing](url)

**Comment by jtuckertw** [comment]
Thank you @jthiel16 !

**Comment by jtuckertw** [comment]
@aguillen1  Would you be able to please upload these to the site instead?

**Comment by aguillen1** [comment]
@jtuckertw Application pictures have been updated
