### ISSUE TITLE
Case Studies AND News Heroes need to be switched out

### ISSUE THREAD

**Issue by jtuckertw** [Tallwave/PIC-Subsalve#211]
Subsalve does not have the royalties for the current images in CS and News

Please use any one of these three options in each spot

https://drive.google.com/open?id=17C1EYqbpcvsAPmzz5NW8cbKMaHZnUwgG

**Comment by aguillen1** [comment]
@jtuckertw Swapped hero images for news (http://subsalve.wpengine.com/news) and Case Studies (http://subsalve.wpengine.com/case-studies)

**Comment by jtuckertw** [comment]
Perfect! - Merci @aguillen1
