### ISSUE TITLE
Remove Image Switch, from all case studies images.

### ISSUE THREAD

**Issue by jtuckertw** [Tallwave/PIC-Subsalve#212]

**Comment by cmoosman1** [comment]
@jtuckertw - Is this the same request as ticket 136? And what are you wanting remove the hover state, the click functionality or remove everything?

**Comment by cmoosman1** [comment]
@jtuckertw - The overlay and click functionality ave been removed

**Comment by jtuckertw** [comment]
Fixed - Thank you @cmoosman1
