### ISSUE TITLE
News Colors are incorrect for Press Releases, should be blue

### ISSUE THREAD

**Issue by jtuckertw** [Tallwave/PIC-Subsalve#213]
![image](https://user-images.githubusercontent.com/45019034/76652911-c9609700-6524-11ea-9edc-d526804803fc.png)

![image](https://user-images.githubusercontent.com/45019034/76652932-d5e4ef80-6524-11ea-82d4-f3aef2973d8e.png)

**Comment by cmoosman1** [comment]
@jtuckertw - Press items show a blue bar on the left hand side of the card

**Comment by jtuckertw** [comment]
Fixed.  Thank you @cmoosman1
