### ISSUE TITLE
Events Are out of order

### ISSUE THREAD

**Issue by jtuckertw** [Tallwave/PIC-Subsalve#214]
![image](https://user-images.githubusercontent.com/45019034/76653238-818e3f80-6525-11ea-8d33-d16ab17c0e4d.png)

April 1 event is showing after the May events.

April 1 Event is in process of being cancelled.  Is "TBD" and option for the date circle where "APR 01" is now input?

**Comment by cmoosman1** [comment]
@jtuckertw - The events are ordered by date.

**Comment by jtuckertw** [comment]
Fixed - Thank you @cmoosman1
