### ISSUE TITLE
Deco Habitat

### ISSUE THREAD

**Issue by jtuckertw** [Tallwave/PIC-Subsalve#217]
Rich wanted to know - is it easy to just remove the Challenge Solution Outcome cards entirely without breaking the page, I told him i did not think so.

Under Construction as titles should revert to Challenge, Solution Outcome
The text below should be "This case study is currently under construction. Please enjoy our photos in the meantime."

**Comment by aguillen1** [comment]
@jtuckertw I would not be able to delete those and dev would probably give you a no on removing those lol
I've updated the verbiage: http://subsalve.wpengine.com/deco-habitat

**Comment by jtuckertw** [comment]
No joke.  @aguillen1   ;-)
Thank you for these changes they should be just fine.
