### ISSUE TITLE
Pipe Plugger Typos

### ISSUE THREAD

**Issue by jtuckertw** [Tallwave/PIC-Subsalve#218]
LOL OK this paint image is a sad joke.

1) Title of column should be "Valve (in.)"
2) First data line should be "Stem"

![image](https://user-images.githubusercontent.com/45019034/77704513-73efa580-6f7a-11ea-885e-3503098fc17c.png)

**Comment by aguillen1** [comment]
@jtuckertw LOL! I love the paint job! This has been updated: http://subsalve.wpengine.com/pipe-pluggers

**Comment by jtuckertw** [comment]
I love the edits!  Thank you!
