### ISSUE TITLE
About US: Wrong Case Studies

### ISSUE THREAD

**Issue by jtuckertw** [Tallwave/PIC-Subsalve#219]
Remove Dubai Voluntary Case Study
Remove Bolivian Navy
Replace both of these with any of the five active Case Studies (Not Deco Habit)

**Comment by aguillen1** [comment]
@jtuckertw Removed and have replaced all the drafts with live case studies http://subsalve.wpengine.com/about-us

**Comment by jtuckertw** [comment]
Beautiful!
