### ISSUE TITLE
Products Cable Floats

### ISSUE THREAD

**Issue by jtuckertw** [Tallwave/PIC-Subsalve#223]
http://subsalve.wpengine.com/cable-floats

Product Specifications listed twice.  Please combine the text with the table into a single Product Specifications box.

![image](https://user-images.githubusercontent.com/45019034/77775430-c3c97d80-7009-11ea-8313-381bbc9619c6.png)

**Comment by aguillen1** [comment]
Hey @jtuckertw Changed that one with the text (screenshot you attached) to read "Product Details" instead as the Product Specifications is where the data table lives. Should I rename "Product Details" to anything else?

**Comment by aguillen1** [comment]
Changed to Additional Product Options!
