### ISSUE TITLE
Enclosed Flotation Bags: Data Updates

### ISSUE THREAD

**Issue by jtuckertw** [Tallwave/PIC-Subsalve#224]
- [x] Please update the data in the Attachment Points table as follows for both Metric and Standard:

EFB 200: 1 bottom
EFB 500: 2 top/1 bottom
EFB 1000: 2 top/1 bottom 
EFB 2000: 2 top/1 bottom
EFB 4000: 2 top/1 bottom
EFB 6000: 3 top/1 bottom

- [x] Please add an empty row between Standard and Metric tables so that thee are on shaded lines

**Comment by aguillen1** [comment]
@jtuckertw These dimensions have ben added to the table: http://subsalve.wpengine.com/enclosed-flotation-bags

**Comment by jtuckertw** [comment]
perfect!  Looks great - thank you!
