### ISSUE TITLE
News: An operating company of Avon Rubber p.l.c.

### ISSUE THREAD

**Issue by jtuckertw** [Tallwave/PIC-Subsalve#227]
Press release  Dumb title…misleading…should be Press Release   Performance Inflatables Company Acquires Avon Engineered Fabrications

**Comment by aguillen1** [comment]
@jtuckertw Hi! Could this task be for AEF? Subsalve doesn't have a news article around this

**Comment by jtuckertw** [comment]
It's on the News page @aguillen1 
http://subsalve.wpengine.com/news

**Comment by aguillen1** [comment]
Ah! I was looking at the homepage carousel. This has been updated @jtuckertw 
http://subsalve.wpengine.com/news

**Comment by jtuckertw** [comment]
Perfect!
