### ISSUE TITLE
Case Studies - Load Remaining 17 Case Studies using Under Construction format

### ISSUE THREAD

**Issue by jtuckertw** [Tallwave/PIC-Subsalve#228]
Using the Deco Habitat case study as the model, please upload and publish the remaining case studies.

**Comment by aguillen1** [comment]
@jtuckertw All case studies have been published

**Comment by jtuckertw** [comment]
OK Will QA

**Comment by jtuckertw** [comment]
Thank you @aguillen1 
@cmoosman1 None of these case studies pages are showing.

**Comment by cmoosman1** [comment]
@jtuckertw - All these are sowing up not awesome in presentation but they are loading the only two that weren't loading TISI and USS Spiegel Grove because they dont ave a "case study", I removed them from the menu. Once those are loaded into WP we can add them back to the menu.

**Comment by jtuckertw** [comment]
Looking good!  TY @cmoosman1 @aguillen1
