### ISSUE TITLE
Assorted Content Issues

### ISSUE THREAD

**Issue by jtuckertw** [Tallwave/PIC-Subsalve#229]
- [x] We had a map link near the standard contact info that is now gone?  No - Out of scope
- [x] Accessories is no longer on the menu? No - Out of Scope

@aguillen1 + 1 for @jthiel16 
- [x] For the calendar of events can the cancelled ones got to 2021 so they go to the end of the list …btw how does that handle years as we only see month/day   ok if it is silent and next year just comes after Dec
- [ ] @jthiel16 / @aguillen1 The IYA-Inflation Yoke Assembly from the catalog disappeared from accessories.  I don't know that we ever had this photo but will check.
- [x] The SP-40 w lifting beam Take the -40 out in both instances so customers are not confused that is only available in one size
- [x] The extra Product Specifications on the cable floats (I see the name changed but not in a way that makes sense to the user)   Lets go with Additional Product Options   Have it occur after the Product Specifications and when it opens it should say See Enclosed Flotation Bags and Salvage Pontoons for heavier objects.  Twin Floats also available
- [x] Replace the airplane photo in about us with the facility attached (crop to zoom in as necessary)  2nd from left in the collage.
- [x] The PF product (Professional Lift Bags)  uses the same photo twice .  Use the attached for one of the photos

Professional Lift Bag here
![DSC08881](https://user-images.githubusercontent.com/45019034/77793009-9939ed80-7026-11ea-988f-fe58204e43b8.jpg)
Facility photo
![20191002_093557](https://user-images.githubusercontent.com/45019034/77793016-9d660b00-7026-11ea-8da2-6bf47a13fdea.jpg)

**Comment by aguillen1** [comment]
@jtuckertw How do I know which ones got cancelled/moved?

from jeff @aguillen1 Psychic powers, I guess?  Sorry, April 1, May 4 , and May 12 have each been cancelled!

**Comment by aguillen1** [comment]
@jtuckertw Updated all of these except the IYA Yoke Assembly accessory!

**Comment by jtuckertw** [comment]
- [ ] Inflation Yoke Assembly is on p.21 of the subsalve catalog.  @jthiel16 http://subsalve.com/wp-content/uploads/2015/01/Subsalve-Catalog-PDF.pdf do we have an original photo for this? Or can a passable version be made for placing on the accessories page?  Thank you
- [ ] aguillen to load IYA photo when provided, please
- [x] Thanks @aguillen1 for the updates above, Rich wanted "Additional Product Options" to be last on the list, following Product Specifications on the Cable Floats Page.  Is that possible?
- [x] Can the Subsalve building image be swapped with the second from the left?  It's current position cuts off what I think Rich wanted to show.

**Comment by aguillen1** [comment]
@jtuckertw 

RE: Additional Product Options comment: This section cannot be swapped with the table as the table is always the final section of the accordion.

RE: Building Image: Image has been swapped: http://subsalve.wpengine.com/about-us

**Comment by jtuckertw** [comment]
Perfect - thank you!
