### ISSUE TITLE
Application Description Cards Updates

### ISSUE THREAD

**Issue by jtuckertw** [Tallwave/PIC-Subsalve#230]
Only the short home page card descriptors have changed.  Each should now fit on the card.

www.subsalve.wpengine.com

[Applications (1).xlsx](https://github.com/Tallwave/PIC-Subsalve/files/4397234/Applications.1.xlsx)

**Comment by aguillen1** [comment]
@jtuckertw All application card content has been updated with the provided information

**Comment by jtuckertw** [comment]
@aguillen1 You did great with these - can you revise three of them so they fit, please?

**Control & Actuation**
Our extensive set of remote actuation and ascent/decent control solutions meet your actuation & control needs

**Public Safety**
Public safety dive teams are challenged to move and recover objects in difficult environements. We are ready to support you.

**Research**
From instrumentation to archeological objects to autonomous systems, we have solutions for your Research needs.

**Comment by aguillen1** [comment]
These edits have been made @jtuckertw http://subsalve.wpengine.com/

**Comment by jtuckertw** [comment]
Thank you! @aguillen1 !
