### ISSUE TITLE
Products: Cable and Pipeline Floats Minor Edit

### ISSUE THREAD

**Issue by jtuckertw** [Tallwave/PIC-Subsalve#232]
@aguillen1 Cable and Pipeline Floats Product Table has 3 columns that should be removed: Height, Length, and Attachment Points.

**Comment by aguillen1** [comment]
@jtuckertw Those columns have been removed: http://subsalve.wpengine.com/cable-floats

**Comment by jtuckertw** [comment]
Thank you! @aguillen1 Looks great!
