### ISSUE TITLE
Accessories - Inflation Yoke Assembly

### ISSUE THREAD

**Issue by jtuckertw** [Tallwave/PIC-Subsalve#234]
@jthiel16 / @aguillen1 The IYA-Inflation Yoke Assembly from the catalog disappeared from accessories. I don't know that we ever had this photo but will check.

**Comment by jthiel16** [comment]
@aguillen1 @jtuckertw Here is the photo:
[https://drive.google.com/file/d/14oXDzad507n-2YiYDtNnrrHZU0VBMEgg/view?usp=sharing](url)

**Comment by aguillen1** [comment]
@jtuckertw Inflation Yoke Assembly has been added as an accessory to Subsalve's website

**Comment by jtuckertw** [comment]
Looks awesome (well, as awesome as an Inflation Yoke Assembly can look...) - thank you both!
@aguillen1 @jthiel16
