### ISSUE TITLE
Weird L-Sep Character on About Us page

### ISSUE THREAD

**Issue by jtuckertw** [Tallwave/PIC-Subsalve#235]

**Comment by cmoosman1** [comment]
@jtuckertw - Can you get me a screen shot?

**Comment by jtuckertw** [comment]
There ya go!  @cmoosman1 

![image](https://user-images.githubusercontent.com/45019034/78594507-4b2ea200-77fd-11ea-8cfc-759c319d7831.png)

**Comment by cmoosman1** [comment]
@jtuckertw - This is resolved, this type of thing is a result of copy paste from word or other txt editors on PC. In a PC environment these txt editors can have hidden characters. If we are doing copy paste it is best to copy paste into notepad and then into WP.

**Comment by jtuckertw** [comment]
Thanks @cmoosman1 
Attn: @aguillen1  for Criss' comments
