### ISSUE TITLE
Asterisks for Under Construction Content

### ISSUE THREAD

**Issue by jtuckertw** [Tallwave/PIC-Subsalve#237]
- [x] Dev to put additional text on Case Study Menus - "See All Case Studies (* Asterisk indicates Under Construction Case Studies)"

- [x] Remove Duplicate Group Ocean Link

- [x] Content to Put asterisks next to under construction links.

**Comment by cmoosman1** [comment]
@jtuckertw - I need clarification on this?

**Comment by jtuckertw** [comment]
@cmoosman1 I didn't assign this out because I wanted to get further guidance from the client.

**Comment by aguillen1** [comment]
@jtuckertw I added asterisks and removed the duplicate Group Ocean on the main menu 👍🏼

**Comment by jtuckertw** [comment]
@aguillen1 Tyvm!
@Cmoosman1  Can you put the additional text for describing the asterisks?
Dev to put additional text on Case Study Menus - "See All Case Studies  (* Asterisk indicates Under Construction Case Studies)"

**Comment by jtuckertw** [comment]
@cmoosman1 This message now appears on the Product page also.  Please remove from Product page.

**Comment by jtuckertw** [comment]
@cmoosman1 The new text has disappeared from the case studies.

**Comment by cmoosman1** [comment]
@jtuckertw - This is resolved in the current build.

**Comment by jtuckertw** [comment]
This looks, Great!  Thank you @cmoosman1
