### ISSUE TITLE
Accessories Image Links

### ISSUE THREAD

**Issue by jthiel16** [Tallwave/PIC-Subsalve#238]
@cmoosman1 @jtuckertw On the accessories page, can we disable the hover-over / link effect from each of the accessory images, since that doesn't go anywhere currently?

**Comment by jtuckertw** [comment]
Thank you, @jthiel16

**Comment by cmoosman1** [comment]
@jtuckertw - This is resolved in the current build

**Comment by jtuckertw** [comment]
FIXED - Thank you @cmoosman1
