### ISSUE TITLE
Use different Pipe Plugger image for Pipe Pluggers Card

### ISSUE THREAD

**Issue by jtuckertw** [Tallwave/PIC-Subsalve#244]
Please use the one entitled "Subsalve Inflated Pipe Plugger as card image.  The current is really poor quality

**Comment by zuzannaczerny** [comment]
@jtuckertw please check out this new image!

**Comment by jtuckertw** [comment]
screenshot?  @zuzannaczerny

**Comment by zuzannaczerny** [comment]
<img width="1672" alt="Screen Shot 2020-04-22 at 2 50 57 PM" src="https://user-images.githubusercontent.com/40444952/80037680-e9cb2c00-84a8-11ea-83ea-2d7b56879303.png">
@jtuckertw

**Comment by jtuckertw** [comment]
Awesome - ty @zuzannaczerny !!!  TYVM!
