### ISSUE TITLE
Logo appears for an extended period of time when navigating pages

### ISSUE THREAD

**Issue by jtuckertw** [Tallwave/PIC-Subsalve#245]
Per client: AARGH testing and now the pause screen comes up on every page change!!!

Client is very annoyed with this.

**Comment by cmoosman1** [comment]
@jtuckertw - Im not seeing this on my local build or in production? I have cleared cache and tested across multiple systems win/mac and chrome/ff/safari/edge.

**Comment by jtuckertw** [comment]
It's not happening any longer.
