### ISSUE TITLE
Header issues in Chrome

### ISSUE THREAD

**Issue by jtuckertw** [Tallwave/PIC-Subsalve#247]
Chrome users typing subsalve.com do not get a resolved page.

(index):1 Access to XMLHttpRequest at 'https://subsalvestage.wpengine.com/wp-json/wp/v2/router' from origin 'https://www.subsalve.com' has been blocked by CORS policy: The 'Access-Control-Allow-Origin' header has a value 'https://subsalve.com' that is not equal to the supplied origin.
subsalvestage.wpengine.com/wp-json/wp/v2/router:1 Failed to load resource: net::ERR_FAILED
createError.js:16 Uncaught (in promise) Error: Network Error
at e.exports (createError.js:16)
at XMLHttpRequest.f.onerror (xhr.js:87)
DevTools failed to load SourceMap: Could not load content for https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.6/umd/popper.min.js.map: HTTP error: status code 522, net::ERR_HTTP_RESPONSE_CODE_FAILURE

**Comment by cmoosman1** [comment]
@jtuckertw - I just pulled this up on my kids Windows 10 machine and every other machine I have in my house

**Comment by cmoosman1** [comment]
Just run tis from GTMetrix. The test would fail if the site wasn't resolving. 
<img width="1385" alt="Screen Shot 2020-04-21 at 7 27 01 PM" src="https://user-images.githubusercontent.com/49693121/79933928-34e03300-8406-11ea-8d11-ca85652e03e1.png">

**Comment by jtuckertw** [comment]
i believe you - but this is what I experience:

https://www.loom.com/share/dd0be96c85894d0e8a28844dd72c56b6

**Comment by jtuckertw** [comment]
Seems to be resolved - TY @cmoosman1
