### ISSUE TITLE
Add COVID-19 to the Mega Menu

### ISSUE THREAD

**Issue by jtuckertw** [Tallwave/PIC-Subsalve#250]
For Subsalve "COVID-19" should replace where Commercial Lift Bags is on the menu.
Commercial Lift Bags should move to the first column.

For AEF COVID 19 should be placed where Emergency Services currently is, shifting all other apps down one position.  Create new column for "Specialty Products" to move into,

**Comment by cmoosman1** [comment]
@jtuckertw - This functionality is completed on the Subsalve site.

**Comment by jtuckertw** [comment]
@cmoosman1 Please place in the correct spot on the Subsalve page.
Was not able to test AEF site for placement - need link to test site.

**Comment by cmoosman1** [comment]
@jtuckertw - Commercial lift bags are a product? Covid-19 is an application they are in different menus?

**Comment by jtuckertw** [comment]
Oops you are correct - Rich is OK with the placement on this menu ticket cancelled
@cmoosman1
