### ISSUE TITLE
Create a COVID-19 Application Page

### ISSUE THREAD

**Issue by jtuckertw** [Tallwave/PIC-Subsalve#251]
This should be among the last tasks we do because it depends on all other work being completed.
Title: COVID-19

This page will contain the following Product Cards:  
Items in parentheses have yet to be given an official name.
(Helmet)  | Power Unit Auxilary Kit | (Emergency Partitions) | Oasis LDU (Liquid Distribution Unit)

**Note: Any links going to the other company's site MUST open in a new window.**
Helmet shall link to the Subsalve page containing Oxygen helmets
PUAK shall link to the AEF page for PUAK
EP shall link to the AEF page for EP
Oasis shall link to the AEF page for Oasis

The following text should be used as the intro text to this application:
Subsalve and its affiliate AEF have a number of standard products suitable for emergency preparedness and a few that we have rapidly retooled to make specifically in response to the Covid-19 crisis.

With over 40 years of experience in supporting customers and the public in times of need such as during hurricane recovery, our team is prepared to help in a crisis.  We have existing products used to deliver emergency potable water and fuel for power generation to temporary camp/hospital installations, and we have delivered thousands of buoyancy products to hurricane recovery efforts.  In response to the current Covid-19 crisis, we have developed the Subsalve Oxygen Treatment hood to lessen the demand on ventilators in hospitals and temporary partitions to provide a level of patient privacy in field hospital installations.  If you have needs for other custom solutions please contact us

**Comment by jtuckertw** [comment]
@cmoosman1 This page will need to be on the AEF and Subsalve sites: 
@zuzannaczerny The following text should be used for the intro to this page:
"Subsalve and its affiliate AEF have a number of standard products suitable for emergency preparedness and a few that we have rapidly retooled to make specifically in response to the Covid-19 crisis.

With over 40 years of experience in supporting customers and the public in times of need such as during hurricane recovery, our team is prepared to help in a crisis. We have existing products used to deliver emergency potable water and fuel for power generation to temporary camp/hospital installations, and we have delivered thousands of buoyancy products to hurricane recovery efforts. In response to the current Covid-19 crisis, we have developed the Subsalve Oxygen Treatment hood to lessen the demand on ventilators in hospitals and temporary partitions to provide a level of patient privacy in field hospital installations. If you have needs for other custom solutions please contact us"

**Comment by zuzannaczerny** [comment]
@jtuckertw updated

**Comment by jtuckertw** [comment]
@zuzannaczerny Weird - this says updated yesterday, but a push was done today and it is not showing on either the AEF or Subsalve sides.  @cmoosman1 can you verify?

**Comment by jtuckertw** [comment]
@cmoosman1 and @zuzannaczerny Subsalve is working AEF is not

Please make sure AEF has the following text that places AEF first
"AEF and its affiliate Subsalve have a number of standard products suitable for emergency preparedness and a few that we have rapidly retooled to make specifically in response to the Covid-19 crisis.

With over 40 years of experience in supporting customers and the public in times of need such as during hurricane recovery, our team is prepared to help in a crisis. We have existing products used to deliver emergency potable water and fuel for power generation to temporary camp/hospital installations, and we have delivered thousands of buoyancy products to hurricane recovery efforts. In response to the current Covid-19 crisis, we have developed the Subsalve Oxygen Treatment hood to lessen the demand on ventilators in hospitals and temporary partitions to provide a level of patient privacy in field hospital installations. If you have needs for other custom solutions please contact us"

**Comment by jtuckertw** [comment]
Fixed
![Uploading image.png…]()
