### ISSUE TITLE
Create and Load Helmet Product Page

### ISSUE THREAD

**Issue by jtuckertw** [Tallwave/PIC-Subsalve#252]
Requirements doc: https://docs.google.com/spreadsheets/d/1NRyi_4EzhJYgq4q4HQGat6xuN3QIiiwLNEM1RWpmxzM/edit#gid=0

PIC Content Folder: https://drive.google.com/drive/folders/1PjM9_k4h8rRyd1nkqJy6yFTZeFS7d-8T

See Document containing all descriptions and categories: https://drive.google.com/file/d/16J5ZwLSkWx7vEY5zPBQy4ydCOO-gUlgb/view

 Determine Primary Image (Client has supplied in PIC COntent Folder/Subsalve
 Load Product Images (Client provided in folder above
 Load Verbiage and Product Details to Page using Description and Category doc above.

**Comment by zuzannaczerny** [comment]
@jtuckertw updated :)

**Comment by jtuckertw** [comment]
- [ ] @cmoosman1 Please center images for this product.

@zuzannaczerny 
- [x] Please Replace text shown below with: "The Subsalve Oxygen Treatment Hood is designed to provide a solution for Non-Invasive Ventilation.  Published studies have shown that Helmet Based Ventilation can lead to a >40% reduction in the demand for ventilators in the treatment of ARDS. (helmetbasedventilation.com).  
Caution: Federal law (USA) restricts this device to sale by, on the order of or to physicians or licensed clinical practitioners."
![image](https://user-images.githubusercontent.com/45019034/80322723-befc1300-87db-11ea-9939-b6784ad50385.png)
- [x] Please Relabel this section as "Ease of Use" and include the rest of the text beneath it.  Do not include the words "Default Open"
![image](https://user-images.githubusercontent.com/45019034/80322862-9294c680-87dc-11ea-95c6-b7a18d009331.png)

**Comment by zuzannaczerny** [comment]
@jtuckertw updated

**Comment by jtuckertw** [comment]
@cmoosman1 Not seeing @zuzannaczerny's changes  - is a push required?

**Comment by cmoosman1** [comment]
@jtuckertw - Im not 100% that its correct but from what I can see looks like everything is updated?

**Comment by cmoosman1** [comment]
@jtuckertw - The images need to be cropped to the correct size, I dont know were those images came from but they look pretty bad in general.

**Comment by jtuckertw** [comment]
@cmoosman1 - everything looks fine now.

**Comment by jtuckertw** [comment]
- [ ] @zuzannaczerny  are you able to crop the images to the correct size, so that they center appropriately?  Please work with Criss and or Jason if specifications are needed.

- [x] @zuzannaczerny Client Requested today that the infographic be linked at the end of the description in the gray blue box, with the following verbiage:  "<link>Subsalve Oxygen treatment Hood Infographic</link> 
Link to Infographic should open in new window: This requirement may not be possible because they provided an image instead of a PDF.  If this is the case, is it simple enough to convert the infographic into a PDF?

- [x] @zuzannaczerny Client Requested today that the video be linked at the end of the description in the gray blue box, with the following verbiage:  "<link>Subsalve Oxygen treatment Hood Video</link> Video Provided courtesy of <link>steerforward.com </link>

Link to Native video: https://drive.google.com/open?id=1-DWK060Prwkl65O3sFE0QH-nW6GfWXAb

**Comment by zuzannaczerny** [comment]
@jtuckertw waiting on PDF

**Comment by jtuckertw** [comment]
[Infographics_Subsalve_4.pdf](https://github.com/Tallwave/PIC-Subsalve/files/4549878/Infographics_Subsalve_4.pdf)

**Comment by jtuckertw** [comment]
Resolved  Link Color is awful
![image](https://user-images.githubusercontent.com/45019034/80566265-7002d900-89a7-11ea-982e-baa87024e886.png)

**Comment by jtuckertw** [comment]
@cmoosman1  I did these last night - the link color looks awful - is it supposed to be like that or did I do something wrong?  Also the links open within same tab, rather than new tab. can that be fixed easily?
