### ISSUE TITLE
Add Helmet to Product Menu on Subsalve

### ISSUE THREAD

**Issue by jtuckertw** [Tallwave/PIC-Subsalve#253]
Client has not provided official name for this yet.  TBD

Not sure if this is dev or content.  Seems like in the past it was Dev.

**Comment by cmoosman1** [comment]
@jtuckertw - This functionality is complete on the Subsalve site

**Comment by jtuckertw** [comment]
@cmoosman1 Please remove Aux Power Kit, Load Oasis, and Emergency Partitions from the Subsalve menu.  These are AEF products.
Please move Oxygen Treatment Hood in alpha order between Mark V and Pipe Pluggers.
![image](https://user-images.githubusercontent.com/45019034/80322488-7859e900-87da-11ea-9d63-3461b8916ab2.png)

**Comment by jtuckertw** [comment]
Perfect - Thank you @cmoosman1
