### ISSUE TITLE
Create News Card with Helmet Video

### ISSUE THREAD

**Issue by jtuckertw** [Tallwave/PIC-Subsalve#254]
Subsalve Offers Oxygen Treatment Hood Product in the fight Against COVID 19

Helmet Video Link for Button
https://vimeo.com/410383791/f2d362a066

**Comment by cmoosman1** [comment]
@jtuckertw - This functionality is complete on the Subsalve site

**Comment by jtuckertw** [comment]
Thank you @cmoosman1 
@aguillen1 and @zuzannaczerny 
Please edit this on the Homepage and News Page
Retitle: Subsalve Offers Oxygen Treatment Hood in Fight Against COVID-19

**Comment by zuzannaczerny** [comment]
Updated

**Comment by zuzannaczerny** [comment]
@jtuckertw updated

**Comment by jtuckertw** [comment]
@zuzannaczerny Perfect on the Homepage but It did not get updated on the News page.
Tagging @cmoosman1 in the event it is a dev issue.

**Comment by zuzannaczerny** [comment]
@jtuckertw I had this same problem yesterday, it wasn't updating on my end.

**Comment by jtuckertw** [comment]
OK thank you @zuzannaczerny  we'll ask @cmoosman1 to take a look to see why the News cards are only updating on the Homepage and not on the News page.

**Comment by cmoosman1** [comment]
@jtuckertw - This is resolved on the news page and the home page.

**Comment by jtuckertw** [comment]
Perfect - thank you @cmoosman1 and @zuzannaczerny Closed
