### ISSUE TITLE
Please add the AEF Product Cards to the Subsalve COVID Application Page 

### ISSUE THREAD

**Issue by jtuckertw** [Tallwave/PIC-Subsalve#255]
- [ ] Please Create and Add Product Cards for PUAK, Partition, and LDU to Subsalve page
- [ ] Please Link Products to their AEF Product Page locations.

**Comment by zuzannaczerny** [comment]
@jtuckertw do these product cards all use the same information as before?

**Comment by jtuckertw** [comment]
@zuzannaczerny Yes, they should be equivalent to the AEF Product Cards - note update the cards on the AEF side first, before doing this task or there will be double work involved.  The latest iteration showing on the website shows each of the product cards needs to be replaced with better or corrected images.

**Comment by zuzannaczerny** [comment]
@jtuckertw for some reason the I got the cards but the images need to be fixed!

**Comment by jtuckertw** [comment]
@Cmoosman1 and @zuzannaczerny Can this be fixed before 9AM?

Both sites still have the incomplete set of products and the incorrect photos.

**Comment by jtuckertw** [comment]
@cmoosman1 I did my best to upload the correct media files into each of the product cards on the corresponding sites, but when I went to test them, they did not render (Can you let me know what I did wrong, please?).  The crosslinked product cards need to be added to each COVID-19 page on each site.

**Comment by cmoosman1** [comment]
@jtuckertw - All crosslinking between sites is working as expected and taking user directly to the page and not the home page

**Comment by jtuckertw** [comment]
awesome - looks great!  TY @cmoosman1
