### ISSUE TITLE
Please revise text on the Alert Banners as follows

### ISSUE THREAD

**Issue by jtuckertw** [Tallwave/PIC-Subsalve#256]
@Criss I'm assigning this to you because I don't think Zuzanna knows where this functionality is.  Please feel free to transfer to her if you can provide her guidance.

Note: Bold Text should be Hyperlinks, not bold text

For Subsalve Banner:
Subsalve USA and its <link>**Performance Inflatables**</link> affiliate <link>**AEF**</link> are engaged in the fight against Covid-19.  While continuing to supply our existing customers with essential products, in a matter of weeks we have developed high impact new products to supplement our existing products used in a variety of emergencies and national disasters.  
In partnership with leading Universities, Research Hospitals and Tech companies we are supporting the development of clinical protocols to aid in the rapid deployment of the Subsalve Oxygen Treatment Hoods.
Please see our <link>**Covid-19**</link> products page for more information

For AEF Banner:
AEF LLC and its <link>**Performance Inflatables**</link> affiliate <link>**Subsalve**</link> are engaged in the fight against Covid-19.  While continuing to supply our existing customers with essential products, in a matter of weeks we have developed high impact new products to supplement our existing products used in a variety of emergencies and national disasters.  
In partnership with leading Universities, Research Hospitals and Tech companies we are supporting the development of clinical protocols to aid in the rapid deployment of the Subsalve Oxygen Treatment Hoods.
Please see our <link>**Covid-19**</link> products page for more information

**Comment by cmoosman1** [comment]
@jtuckertw - This is completed and on dev

**Comment by jtuckertw** [comment]
@cmoosman1 Performance Inflatables, AEF, and Subsalve each need to be hyperlinks

**Comment by jtuckertw** [comment]
@cmoosman1 thank you!
