### ISSUE TITLE
Please revise the Oxygen Treatment Hood Description Text as Follows

### ISSUE THREAD

**Issue by jtuckertw** [Tallwave/PIC-Subsalve#257]
![image](https://user-images.githubusercontent.com/45019034/80531322-474ef500-894f-11ea-974e-0c4b6c120a58.png)

[add BEFORE the caution, where the yellow arrow is pointing]
Bold text should be an HTML link not bold.

If you wish to place a small retail order online you can go to <link>**oxygentreatmenthoods.com**</link>.  For larger institutional orders please contact us directly using the contact form at the bottom of the page.

**Comment by zuzannaczerny** [comment]
@jtuckertw updated

**Comment by jtuckertw** [comment]
Links are not working @cmoosman1  - The pointer changes as if it is a link but no navigation occurs.

https://subsalvedev.wpengine.com/helmet

**Comment by cmoosman1** [comment]
@jtuckertw - This is resolved in dev.

**Comment by jtuckertw** [comment]
Looks good! Thank you @cmoosman1
