### ISSUE TITLE
Oxygen Hood FDA comments need to be shown in an open container

### ISSUE THREAD

**Issue by jtuckertw** [Tallwave/PIC-Subsalve#259]
2) Lines 1,7,8,9 Oxygen Hood should be switched from Ease of Use to Prod Specs if EOU container cannot default open.

**Comment by cmoosman1** [comment]
@jtuckertw - This is resolved in the current production build.
<img width="1441" alt="Screen Shot 2020-05-04 at 10 33 56 AM" src="https://user-images.githubusercontent.com/49693121/80995266-da29dc80-8df2-11ea-9060-8910218646bf.png">
