### ISSUE TITLE
Prodcuts overview page:

### ISSUE THREAD

**Issue by jtuckertw** [Tallwave/PIC-Subsalve#26]
Let's reduce the space between the end of the product cards and the start of the Applications cards. Right now it's a bit much.

https://drive.google.com/file/d/17pC68W4VcmaWgv3PofJdKnB4TuiJHG5J/view?usp=sharing

**Comment by cmoosman1** [comment]
@jtuckertw - This is resolved in the current build

**Comment by jthiel16** [comment]
I'm still seeing a lot of extra space

**Comment by cmoosman1** [comment]
@jtuckertw  - This is resolved in the current build

**Comment by jtuckertw** [comment]
@jthiel Please re-validate and close if good.  Thanks!

**Comment by jthiel16** [comment]
Looks good, thank you
