### ISSUE TITLE
Products overview page:

### ISSUE THREAD

**Issue by jtuckertw** [Tallwave/PIC-Subsalve#27]
The blue text links look like they might be the wrong blue.

Should be #0076be

https://drive.google.com/file/d/17nN8mubtKfjBnMsi3SMQg4S1J3YTKkX8/view?usp=sharing

**Comment by cmoosman1** [comment]
@jtuckertw - This is resolved in the current build

**Comment by jtuckertw** [comment]
@jthiel16 Please revalidate and close if it looks good - thanks!
