### ISSUE TITLE
About Us page, In the Our History section:

### ISSUE THREAD

**Issue by jtuckertw** [Tallwave/PIC-Subsalve#3]
• The up/down arrows aren't working for me

• Let's only highlight in yellow the one year that you're viewing (vs all years to that point)

• Let's end the vertical line at the last year

• Can we have the height of the white background auto-adjust to the amount of text entered?

https://drive.google.com/file/d/18uL3XlO2I0TDwSgci45jxO_pbBJzay-1/view?usp=sharing

**Comment by cmoosman1** [comment]
@jtuckertw - This is resolved in the current build

**Comment by jtuckertw** [comment]
@jthiel Please re-validate and close if good.  Thanks!

**Comment by jthiel16** [comment]
@cmoosman1 @jtuckertw 
The first bullet was addressed, but I'm stilling seeing the other 3 issues:

• Let's only highlight in yellow the one year that you're viewing (vs all years to that point)

• Let's end the vertical line at the last year

• Can we have the height of the white background auto-adjust to the amount of text entered?

**Comment by cmoosman1** [comment]
@jtuckertw - 2 is done 1 and 3 are pretty considerable refactors at this point Im pushing back on those.

**Comment by jtuckertw** [comment]
Won't fix - low priority. Closing
