### ISSUE TITLE
Home page, mobile, in the Our Products section:

### ISSUE THREAD

**Issue by jtuckertw** [Tallwave/PIC-Subsalve#30]
• The search icon is overlapping the search text

• The description text within each card is breaking outside of it

https://drive.google.com/file/d/17lR5nk1rhz9jqnPPwO_nagloY-lZUlAr/view?usp=sharing

**Comment by cmoosman1** [comment]
@jtuckertw - This is resolved in the current build

**Comment by jtuckertw** [comment]
@jthiel16 Please re-validate and close if all is good. Thanks!
