### ISSUE TITLE
Home page, logo slider component:

### ISSUE THREAD

**Issue by jtuckertw** [Tallwave/PIC-Subsalve#31]
When viewing on mobile, the logos get so tiny. Can we limit the logos to 2 at a time on smaller screens, to keep them legible

https://drive.google.com/file/d/17aBY4VX1udj1mQBB-rcz15RXGgJZCjKa/view?usp=sharing

**Comment by cmoosman1** [comment]
@jtuckertw - This is resolved in the current build

**Comment by jtuckertw** [comment]
Fixed - Close
