### ISSUE TITLE
Upcoming Events component:

### ISSUE THREAD

**Issue by jtuckertw** [Tallwave/PIC-Subsalve#35]
When I hover over the text link, it goes to white/disappears. It also looks like it might be the wrong blue.

Let's change the text link color to #0076be, and hover to #ababab

https://drive.google.com/file/d/17RiZdwJky9tMGE06LBhEQbpkpJWHulJ_/view?usp=sharing

**Comment by cmoosman1** [comment]
@jtuckertw - This is resolved in the current build.

**Comment by jtuckertw** [comment]
@jthiel16 Please validate and close if all is good - thanks!

**Comment by jthiel16** [comment]
@cmoosman1 Can we also have the icon hover to #ababab? It's kinda weird that it doesn't do the same thing as the text

**Comment by jtuckertw** [comment]
@jthiel16 Please validate and close if all is good - thanks!

**Comment by jthiel16** [comment]
Looks good, thanks
