### ISSUE TITLE
Home page, at the bottom of both the Accessories and Case Study sections, let's increase the space after the button by about double, to give the section content some breathing room before the next section starts.

### ISSUE THREAD

**Issue by jtuckertw** [Tallwave/PIC-Subsalve#36]
https://drive.google.com/file/d/17Q3Pj5jCv0jFKq_EFVuTtV6-C8OgwVkC/view?usp=sharing
https://drive.google.com/file/d/17Pc2yLskxzsYfN1yV652J3BSCfrWfm7C/view?usp=sharing

**Comment by cmoosman1** [comment]
@jtuckertw - This is resolved in the current build

**Comment by jthiel16** [comment]
Looks good, thanks Criss
