### ISSUE TITLE
Home page, in the "our products" card section:

### ISSUE THREAD

**Issue by jtuckertw** [Tallwave/PIC-Subsalve#39]
With a keyword entered into search field, let's give the search results title a bold text treatment (to help with readability)

And also left-align the results with the title "Search Results..." at the top. 

https://drive.google.com/file/d/17MHvTosvsYdMLYgBS9wsaSra6p-XkIl_/view?usp=sharing

**Comment by cmoosman1** [comment]
@jtuckertw - This is resolved in the current build

**Comment by jthiel16** [comment]
@jtuckertw @cmoosman1 I'm still seeing the issue

**Comment by cmoosman1** [comment]
@jtuckertw - This is resolved in the current build

**Comment by jtuckertw** [comment]
@jthiel Please re-validate.  Thanks!

**Comment by jthiel16** [comment]
@cmoosman1 Can we left-align this text?

<img width="421" alt="Screen Shot 2019-11-12 at 9 42 43 AM" src="https://user-images.githubusercontent.com/35710312/68691692-64267600-0531-11ea-936f-32953a663b72.png">

**Comment by jtuckertw** [comment]
Fixed
