### ISSUE TITLE
Home page, in the "Our Products" card section, a few things:

### ISSUE THREAD

**Issue by jtuckertw** [Tallwave/PIC-Subsalve#41]
• The icons are looking a bit small, and also off-center. Can we enlarge just a bit and then center

• The heading text is too tight to the top of the card. Ideally would like the same padding on top as there is on the left side. The AEF site looks good as far as that's concerned.

• The cards themselves are too spread out vertically. Should have the same distance between cards as there is horizontally. Looks good on AEF

• I like the hover animation you did here. Can we do the same for AEF?

https://drive.google.com/file/d/17C34FYJX_j9fRVky7gjJgBn-fEZV2_Z7/view?usp=sharing

**Comment by cmoosman1** [comment]
@jtuckertw - This is resolved in the current build

**Comment by jtuckertw** [comment]
@Jthiel - Please review and close if this looks good.  Thanks!

**Comment by jthiel16** [comment]
@cmoosman1 

• The heading text is too tight to the top of the card. Ideally would like the same padding on top as there is on the left side. The AEF site looks good as far as that's concerned.

• The cards themselves are too spread out vertically. Should have the same distance between cards as there is horizontally. Looks good on AEF

cc @jtuckertw

**Comment by jtuckertw** [comment]
@jthiel - Please review and close if this looks good. Thanks!

**Comment by jthiel16** [comment]
Looks great, thanks!
