### ISSUE TITLE
Mobile Nav:

### ISSUE THREAD

**Issue by jtuckertw** [Tallwave/PIC-Subsalve#44]
The hamburger and X icons are too big and vertically off-center within the white navbar. The logo is also a bit off-center vertically. I think we could just shorten the white navbar.

With the nav open, the yellow "download" button goes off the screen to the right:

https://drive.google.com/file/d/174vE9FRnClE9bffS2vrBw4T2kPUWDCGd/view?usp=sharing
https://drive.google.com/file/d/174wQZshIEPPhOMyUfyrATMCsIQkU7tbZ/view?usp=sharing

**Comment by cmoosman1** [comment]
@jtuckertw - This is resolved in the current build

**Comment by jtuckertw** [comment]
@jthiel16 Please validate and close if all is good - thanks!

**Comment by jthiel16** [comment]
@cmoosman1 The hamburger and X icons are still big, and could be reduced by about 20% or so.

**This is a major bug:** Also having a functionality issue with the mobile menu opened, when I tap on "Products" and try to scroll down to see the list, the menu closes unexpectedly.

cc @jtuckertw
