### ISSUE TITLE
In the Main Nav dropdown, when hovering over "Applications":

### ISSUE THREAD

**Issue by jtuckertw** [Tallwave/PIC-Subsalve#50]
A few minor things ...

• There is some slight spacing inconsistency happening with the placement of the "See Accessories" link, when compared to the Products dropdown. Can we move "See Accessories" up a bit to match vertical location on the Products dropdown.

• The icon next to "See Accessories" should be an arrow (instead of external link icon). 

• We could also reduce the space between that text and the icon by about half (all instances).

https://drive.google.com/file/d/17-IhVNRKMzgcjVKcAJi2jzXG51BLMUG0/view?usp=sharing

**Comment by cmoosman1** [comment]
@jtuckertw - This is resolved in the current build

**Comment by jtuckertw** [comment]
@jthiel - Would you please revalidate and close if all looks good.

**Comment by jthiel16** [comment]
@cmoosman1 In the Applications mega menu dropdown:

• The icon next to "See Accessories" should be an arrow (instead of external link icon) like it is under the Products dropdown

cc @jtuckertw

**Comment by jtuckertw** [comment]
Fixed
