### ISSUE TITLE
In the Main Nav dropdown, when hovering over "Products":

### ISSUE THREAD

**Issue by jtuckertw** [Tallwave/PIC-Subsalve#51]
Can we move "See All Accessories" and "See Custom Solutions" both slightly to the left, so that they line up with the text links above?

Also, the vertical line separating those two links is a different color than the horizontal line. Let's make them both the same color (the brighter one)

https://drive.google.com/file/d/16wzAJhh9gb7Ph7qWhwo76Pl80L-jyOY7/view?usp=sharing

**Comment by cmoosman1** [comment]
@jtuckertw - This is resolved in the current build

**Comment by jtuckertw** [comment]
@jthiel16 Please validate and close if all is good - thanks!

**Comment by jthiel16** [comment]
@cmoosman1 The vertical line separating these two links is a different color than the horizontal line above them. Let's make them both the same color (the brighter one). 
Alignment looks good.

<img width="622" alt="Screen Shot 2019-11-15 at 11 41 37 AM" src="https://user-images.githubusercontent.com/35710312/68967314-2037a900-079d-11ea-80bb-327dbdfb32c3.png">

cc @jtuckertw

**Comment by jtuckertw** [comment]
@jthiel16 Please validate and close if all is good - thanks!
