### ISSUE TITLE
In the Main Nav dropdown, when hovering over "Applications":

### ISSUE THREAD

**Issue by jtuckertw** [Tallwave/PIC-Subsalve#52]
Let's have the heading text just say "Applications" instead of "See All Applications", and then remove the link to a separate page. 

There is no overall Applications page as of now.

https://drive.google.com/file/d/16t5JpEmdmd5fLU_aSU06vMPvXG5VDXj6/view?usp=sharing

**Comment by cmoosman1** [comment]
@jtuckertw - This is resolved in the current build

**Comment by jtuckertw** [comment]
Fived - Closed
