### ISSUE TITLE
Home page, in the "Trusted By" logo carousel section:

### ISSUE THREAD

**Issue by jtuckertw** [Tallwave/PIC-Subsalve#53]
The background pattern looks like it isn't quite covering the entire container, and each of the four corners show a small white spec:

https://drive.google.com/file/d/16rnzXVB5bmLgwSl2mPCDuWziz_9z_kT6/view?usp=sharing

**Comment by cmoosman1** [comment]
@jtuckertw - This is resolved in the current build

**Comment by jtuckertw** [comment]
Fixed - Closed
