### ISSUE TITLE
Some of the pill-shaped buttons are showing the text not centered vertically within it. I'm seeing it in the "Download Catalog" button in the main nav, and also in the News section card CTA's

### ISSUE THREAD

**Issue by jtuckertw** [Tallwave/PIC-Subsalve#54]
Let's vertically center these:
https://drive.google.com/file/d/16qO_PKh0pRiyK7YUPntGQ0t9T2GA8JLM/view?usp=sharing
https://drive.google.com/file/d/16oiyWlyC_UgU1yq65GA3qGfAryJuya-s/view?usp=sharing

**Comment by cmoosman1** [comment]
@jtuckertw - This is resolved in the current build

**Comment by jtuckertw** [comment]
Fixed - Closed
