### ISSUE TITLE
On the home page, in the Accessories section ...

### ISSUE THREAD

**Issue by jtuckertw** [Tallwave/PIC-Subsalve#56]
This section should only show the first 4 Accessories in one row. Right now it's showing all  18 of them. We can show all of them on the actual Accessories page.

The images are also coming in too large, so it's showing only 2 per row (instead of 4)

https://drive.google.com/file/d/16b3yqBpj36aGIrW9wRMsT0IY8-ZenR-h/view?usp=sharing

**Comment by cmoosman1** [comment]
@jtuckertw - This is resolved in the current build
