### ISSUE TITLE
Visual : The hamburger menu subtab has text overflowing the boundaries

### ISSUE THREAD

**Issue by adamsisneros** [Tallwave/PIC-Subsalve#57]
Severity: Major
Location: Hamburger menu
OS / OS Version: Global Phones
Device / Browser: Global Phones 
 
Expected Results: 
  When the user accesses the hamburger menu, the menu will have all the links and text in a neat fashion.
 
Actual Results: 
  When the user accesses the hamburger menu on mobile, the subtab shows the text overflowing the menu
 
Steps To Reproduce: 
	1. Launch http://subsalve.wpengine.com/ in HTC 10
	2. Tap the hamburger menu
	3. Tap a subtab
	4. Observe the text overflowing
 
Notes: N/A

Rate of Reproduction: 100%

![Subtab Issue](https://user-images.githubusercontent.com/10537386/66343908-d63fe580-e909-11e9-837e-9653abd52213.png)

**Comment by cmoosman1** [comment]
@jtuckertw - This is resolved in the current build

**Comment by jtuckertw** [comment]
Fixed - Closed
