### ISSUE TITLE
Functionality : Hamburger menu subtabs close when the user scrolls

### ISSUE THREAD

**Issue by adamsisneros** [Tallwave/PIC-Subsalve#58]
Severity: Major
Location: Hamburger menu
OS / OS Version: Global Mobile
Device / Browser: Global Mobile
 
Expected Results: 
  When the user opens a subtab in the hamburger menu, the subtab will stay open until the user taps it again.
 
Actual Results: 
  When the user opens a subtab then scrolls the menu, the subtab closes.
 
Steps To Reproduce: 
	1. Launch http://subsalve.wpengine.com/ on HTC 10
	2. Tap the hamburger menu
	3. Tap a subtab
	4. Scroll down the page
	5. Observe the subtab closes
 
Notes: N/A

Rate of Reproduction: 100%
![Subtab Issue](https://user-images.githubusercontent.com/10537386/66344073-23bc5280-e90a-11e9-8fcd-f79e086d8e22.png)

**Comment by cmoosman1** [comment]
@jtuckertw - This is resolved in the current build

**Comment by jtuckertw** [comment]
Duplicate - not fixed.
