### ISSUE TITLE
Functionality : The user can zoom out of the page to reveal lots of empty space

### ISSUE THREAD

**Issue by adamsisneros** [Tallwave/PIC-Subsalve#59]
Severity: Major
Location: Homepage
OS / OS Version: Global Phones
Device / Browser: Global Phones
 
Expected Results: 
  When the user navigates the site on a phone, all assets and features will scale properly.
 
Actual Results: 
  When the user navigates the site on a phone, the site allows the user to zoom out and show a lot of blank space.
 
Steps To Reproduce: 
	1. Launch http://subsalve.wpengine.com/ on HTC 10
	2. Zoom out
	3. Observe the empty space
 
Notes: N/A

Rate of Reproduction: 100%
![Zoomout Issue](https://user-images.githubusercontent.com/10537386/66344137-477f9880-e90a-11e9-9e1a-4d633e628a2b.png)

**Comment by cmoosman1** [comment]
@jtuckertw - This is resolved in the current build

**Comment by jtuckertw** [comment]
Fixed - Closed
