### ISSUE TITLE
Functionality : The products section shows buttons with text overflowing

### ISSUE THREAD

**Issue by adamsisneros** [Tallwave/PIC-Subsalve#60]
Severity: Major
Location: Homepage -> Our Products section
OS / OS Version: Global Mobile
Device / Browser: Global Mobile
 
Expected Results: 
  When the user navigates the site on a mobile device, the site will scale properly.
 
Actual Results: 
  When the user navigates the site on a mobile device, the Our Products section shows buttons with text overflowing.
 
Steps To Reproduce: 
	1. Launch http://subsalve.wpengine.com/ on HTC 10
	2. Scroll down to Our Products
	3. Observe the buttons with test overflowing
 
Notes: N/A

Rate of Reproduction: 100%
![Products Issue](https://user-images.githubusercontent.com/10537386/66344183-6bdb7500-e90a-11e9-86a4-c568705ece4d.png)

**Comment by cmoosman1** [comment]
@jtuckertw - This is resolved in the current build

**Comment by jtuckertw** [comment]
Fixed - Closed
