### ISSUE TITLE
 Visual : The download catalog button and text above not centered for mobile

### ISSUE THREAD

**Issue by adamsisneros** [Tallwave/PIC-Subsalve#61]
Severity: Major
Location: Homepage -> Accessories section
OS / OS Version: Global Phones
Device / Browser: Global Phones
 
Expected Results: 
  When the user navigates the site on a phone, the site will scale properly.
 
Actual Results: 
  When the user navigates the site on a phone, the images in the Accessories section are cut-off.
 
Steps To Reproduce: 
	1. Launch http://subsalve.wpengine.com/ on HTC 10
	2. Scroll down to Accessories
	3. Observe the images being cut-off
 
Notes: N/A

Rate of Reproduction: 100%
![Accessories Issue](https://user-images.githubusercontent.com/10537386/66344229-8dd4f780-e90a-11e9-90e4-37cdf8eebc79.png)

**Comment by cmoosman1** [comment]
@jtuckertw - This is resolved in the current build

**Comment by jtuckertw** [comment]
@jthiel16 This was not your issue originally but can you take a look?  It seems like the images should be centered - currently they are left justified.  Further down on the page, the Catalog text looks like it also needs to be centered.  Would you agree?

**Comment by jthiel16** [comment]
@jtuckertw @cmoosman1 The Accessory cards looks good to me on the home page, but they aren't centered on the rest of the pages. For example, here's how they look on one of the product detail page (http://subsalve.wpengine.com/aircraft-lift-bags). Recommend centering them like it is on the home page.

<img width="376" alt="Screen Shot 2019-11-15 at 1 35 06 PM" src="https://user-images.githubusercontent.com/35710312/68973966-c6d77600-07ac-11ea-8379-c29f4765915d.png">

And I agree @jtuckertw I think that catalog text and button would look better if centered on small screens

**Comment by jtuckertw** [comment]
Catalog button and text not centered let's demo it.  @cmoosman1

**Comment by jtuckertw** [comment]
Resolved.
