### ISSUE TITLE
Visual : The news tab does not scale on mobile

### ISSUE THREAD

**Issue by adamsisneros** [Tallwave/PIC-Subsalve#62]
Severity: Major
Location: Homepage -> News section
OS / OS Version: Global Phones
Device / Browser: Global Phones
 
Expected Results: 
  When the user navigates the site on a mobile device, the site will scale properly.
 
Actual Results: 
  When the user navigates the site on a mobile device, the News section does not scale at all.
 
Steps To Reproduce: 
	1. Launch http://subsalve.wpengine.com/ on HTC 10
	2. Scroll down to News
	3. Observe the section isn't scaling properly
 
Notes: N/A

Rate of Reproduction: 100%
![News Scaling Issue](https://user-images.githubusercontent.com/10537386/66344292-ae04b680-e90a-11e9-8a59-c97b35997f76.png)

**Comment by cmoosman1** [comment]
@jtuckertw - this is resolved in the current build

**Comment by cmoosman1** [comment]
@jtuckertw - Wrong ticket

**Comment by cmoosman1** [comment]
@jtuckertw - This is resolved in the current build

**Comment by jtuckertw** [comment]
Fixed - Closed
