### ISSUE TITLE
Visual : The Trusted By section has images that are too small

### ISSUE THREAD

**Issue by adamsisneros** [Tallwave/PIC-Subsalve#63]
Severity: Major
Location: Homepage -> Trusted By section
OS / OS Version: Global Phones
Device / Browser: Global Phones
 
Expected Results: 
  When the user navigates the site on a phone, the site will scale properly.
 
Actual Results: 
  When the user navigates the site with on a phone, the Trusted By section has images that are too small
 
Steps To Reproduce: 
	1. Launch http://subsalve.wpengine.com/ on HTC 10
	2. Scroll down to Trusted By
	3. Observe the images aren't scaling properly
 
Notes: N/A

Rate of Reproduction: 100%
![Trusted By Issue](https://user-images.githubusercontent.com/10537386/66344363-e60bf980-e90a-11e9-8b55-e82d225980f8.png)

**Comment by cmoosman1** [comment]
@jtuckertw - This is resolved in the current build

**Comment by jtuckertw** [comment]
Fixed - Closed
