### ISSUE TITLE
Visual : The homepage on iPad has the header image too small on the sides

### ISSUE THREAD

**Issue by adamsisneros** [Tallwave/PIC-Subsalve#64]
Severity: Major
Location: Homepage
OS / OS Version: iPad Air 2
Device / Browser: iOS 12.3
 
Expected Results: 
  When the user navigates the site on tablets, the site will scale correctly
 
Actual Results: 
  When the user navigates the homepage on iPad, the first image is scaled incorrectly
 
Steps To Reproduce: 
	1. Launch http://subsalve.wpengine.com/  on iPad Air 2
	2. Observe the image is scaled incorrectly
 
Notes: N/A

Rate of Reproduction: 100%
![Homepage Image Issue](https://user-images.githubusercontent.com/10537386/66344397-05a32200-e90b-11e9-9abf-491bb0f8c50a.PNG)

**Comment by cmoosman1** [comment]
@jtuckertw - This is resolved in the current build

**Comment by jtuckertw** [comment]
Fixed - Closed
