### ISSUE TITLE
Visual : The Magnifying  Glass image is covering text

### ISSUE THREAD

**Issue by adamsisneros** [Tallwave/PIC-Subsalve#65]
Severity: Major
Location: Homepage
OS / OS Version: iOS 12.3
Device / Browser: iPad Air 2
 
Expected Results: 
  When the user navigates the site, all assets are correctly placed and don't cover other assets unless intended
 
Actual Results: 
  When the user navigates the homepage on iPad Air 2, the Magnifying  Glass icon is covering the search text under Our Products.
 
Steps To Reproduce: 
	1. Launch http://subsalve.wpengine.com/  on iPad Air 2
	2. Scroll down to the Our Products section
	3. Observe the search text is covered by the Magnifying Glass
 
Notes: N/A

Rate of Reproduction: 100%
![Magnifying glass Issue](https://user-images.githubusercontent.com/10537386/66344433-23708700-e90b-11e9-959e-33d07bb121ec.PNG)

**Comment by cmoosman1** [comment]
@jtuckertw - This is resolved in the current build

**Comment by jtuckertw** [comment]
perfect!
