### ISSUE TITLE
Visual : The Text and Buttons on the Homepage are broken on iPad Air 2

### ISSUE THREAD

**Issue by adamsisneros** [Tallwave/PIC-Subsalve#66]
Severity: Major
Location: Homepage
OS / OS Version: iOS 12.3
Device / Browser: iPad Air 2
 
Expected Results: 
  When the user navigates the site on tablets, the site will scale correctly
 
Actual Results: 
  When the user navigates the homepage on iPad, the header text and button is broken or cut-off
 
Steps To Reproduce: 
	1. Launch http://subsalve.wpengine.com/  on iPad Air 2
	2. Observe the text and button is scaled incorrectly
 
Notes: N/A

Rate of Reproduction: 100%
![Text-Button iPad Issue](https://user-images.githubusercontent.com/10537386/66344479-413dec00-e90b-11e9-89fc-b1765e4d00c3.PNG)

**Comment by cmoosman1** [comment]
@jtuckertw - This is resolved in the current build

**Comment by jtuckertw** [comment]
Fixed - Closed Tested via Developer tools.
