### ISSUE TITLE
Text : Follow is misspelt in the footer

### ISSUE THREAD

**Issue by adamsisneros** [Tallwave/PIC-Subsalve#67]
Severity: Trivial
Location: Footer
OS / OS Version: Global
Device / Browser: Global
 
Expected Results: 
  The footer shows multiple links, and social links with the header above saying  "Follow Us"
 
Actual Results: 
  The text "Follow Us" shows a typo with "Folow" instead.
 
Steps To Reproduce: 
	1. Launch http://subsalve.wpengine.com/ on any supported device
	2. Scroll down to the footer
	3. Observe the typo "Folow"
 
Notes: N/A

Rate of Reproduction: 100%
![Typo Follow](https://user-images.githubusercontent.com/10537386/66344523-5dda2400-e90b-11e9-9992-969e98121e5e.png)

**Comment by TheNewWallace** [comment]
@jtuckertw i did check to see if i could edit this and i was not able to

**Comment by cmoosman1** [comment]
@jtuckertw - This is resolved in the current build
