### ISSUE TITLE
Functionality : The down arrow next to Our History has no function

### ISSUE THREAD

**Issue by adamsisneros** [Tallwave/PIC-Subsalve#68]
Severity: Major
Location: About Us -> Our History
OS / OS Version: Global
Device / Browser: Global
 
Expected Results: 
  When the user taps the arrows next to Our History, the site goes to the next or previous history event
 
Actual Results: 
  When the user taps the down arrow, the site does not react.
 
Steps To Reproduce: 
	1. Launch http://subsalve.wpengine.com/about-us on any supported platform
	2. Scroll down to Our History
	3. Tap the down arrow
	4. Observe the site does nothing
 
Notes: N/A

Rate of Reproduction: 100%
![History Arrow Issue](https://user-images.githubusercontent.com/10537386/66344585-7b0ef280-e90b-11e9-9bd1-f39684d42dd2.PNG)

**Comment by cmoosman1** [comment]
@jtuckertw - This is resolved in the current build

**Comment by jtuckertw** [comment]
Fixed - Closed
