### ISSUE TITLE
Visual : The Contact Us section on the homepage is scaled incorrectly on iPad

### ISSUE THREAD

**Issue by adamsisneros** [Tallwave/PIC-Subsalve#69]
Severity: Major
Location: Homepage -> Contact Us
OS / OS Version: iOS 12.3
Device / Browser: iPad Air 2
 
Expected Results: 
  When the user navigates the site on tablets, the site will scale correctly
 
Actual Results: 
  When the user navigates the homepage on iPad, the Contact Us section is scaled incorrectly
 
Steps To Reproduce: 
	1. Launch http://subsalve.wpengine.com/  on iPad Air 2
	2. Scroll to contact us section
	3. Observe the text is overlapped by the input fields
 
Notes: N/A

Rate of Reproduction: 100%
![ContactUs iPad Air Issue](https://user-images.githubusercontent.com/10537386/66344916-28820600-e90c-11e9-9949-fcd13090806c.PNG)

**Comment by jtuckertw** [comment]
Fixed - Closed
