### ISSUE TITLE
About us page:

### ISSUE THREAD

**Issue by jtuckertw** [Tallwave/PIC-Subsalve#7]
In the "Case Studies" section (and any time this component shows up, other than the Case Studies page), let's limit the number of case studies shown to 3. Right now we're showing 4

https://drive.google.com/file/d/18hd7DocJIzREu6yk2Wd_b8uAXT2I-pzE/view?usp=sharing

**Comment by cmoosman1** [comment]
@jtuckertw - This is resolved in the current build

**Comment by jtuckertw** [comment]
CLosed-Fixed
