### ISSUE TITLE
Visual : Products overlap one another on Our Products page

### ISSUE THREAD

**Issue by adamsisneros** [Tallwave/PIC-Subsalve#70]
Severity: Major
Location: Our Products
OS / OS Version: Global Tablet
Device / Browser: Global Tablet
 
Expected Results: 
  When the user navigates the site on tablets, the site will scale correctly
 
Actual Results: 
  When the user navigates the Our Products page on iPad, products overlap each other
 
Steps To Reproduce: 
	1. Launch http://subsalve.wpengine.com/products on iPad Air 2
	2. Observe the products overlapping
 
Notes: N/A

Rate of Reproduction: 100%
![Product Overlap](https://user-images.githubusercontent.com/10537386/66349153-751e0f00-e915-11e9-9674-fe0b3d2a05e9.PNG)

**Comment by cmoosman1** [comment]
@jtuckertw - This is resolved in the current build
