### ISSUE TITLE
Visual : The X button is covered by the Hamburger menu

### ISSUE THREAD

**Issue by adamsisneros** [Tallwave/PIC-Subsalve#71]
Severity: Minor
Location: Hamburger Menu
OS / OS Version: iOS 12.3
Device / Browser: iPad Air 2
 
Expected Results: 
  When the user navigates the site on tablets, the site will scale correctly
 
Actual Results: 
  When the user navigates the homepage on iPad, the close button for the hamburger menu is obscured by the menu
 
Steps To Reproduce: 
	1. Launch http://subsalve.wpengine.com/  on iPad Air 2
	2. Tap the Hamburger Menu
	3. Observe the hamburger menu close button
 
Notes: N/A

Rate of Reproduction: 100%
![Obscured Close Button](https://user-images.githubusercontent.com/10537386/66350035-7819ff00-e917-11e9-95d3-b48c491b6f6b.PNG)

**Comment by cmoosman1** [comment]
@jtuckertw - This is resolved in the current build

**Comment by jtuckertw** [comment]
Fixed - Closed
