### ISSUE TITLE
Visual : The image carousel on the product pages aren't scaling well

### ISSUE THREAD

**Issue by adamsisneros** [Tallwave/PIC-Subsalve#72]
Severity: Major
Location: Product pages
OS / OS Version: Global Mobile
Device / Browser: Global Mobile
 
Expected Results: 
  When the user navigates the site on mobile, the site will scale correctly
 
Actual Results: 
  When the user navigates the site on mobile, the product pages image carousel is scaled incorrectly
 
Steps To Reproduce: 
	1. Launch http://subsalve.wpengine.com/aircraft-lift-bags on any supported mobile device
	2. Scroll down to the image carousel
	3. Observe the module has multiple scaling issues
 
Notes: N/A

Rate of Reproduction: 100%
![Product Image Carousel](https://user-images.githubusercontent.com/10537386/66351481-e2806e80-e91a-11e9-8c61-d4db68f96ea6.jpg)

**Comment by cmoosman1** [comment]
@jtuckertw - This is resolved in the current build

**Comment by jtuckertw** [comment]
Looks good so far.  Keeping open to do full testing.
