### ISSUE TITLE
 Visual : Table isn't shown correctly on mobile devices

### ISSUE THREAD

**Issue by adamsisneros** [Tallwave/PIC-Subsalve#73]
Severity: Major
Location: Product Pages
OS / OS Version: Global Mobile
Device / Browser: Global Mobile
 
Expected Results: 
  When the user navigates the site on tablets, the site will scale correctly
 
Actual Results: 
  When the user navigates the product page on mobile, any tables in the product details section is incorrectly scaled
 
Steps To Reproduce: 
	1. Launch http://subsalve.wpengine.com/aircraft-lift-bags on iPad Air 2
	2. Scroll down to Product Details
	3. Tap Product specifications
	4. Observe the table is incorrectly scaled
 
Notes: N/A

Rate of Reproduction: 100%
![Table Incorrectly Scaled](https://user-images.githubusercontent.com/10537386/66352946-14df9b00-e91e-11e9-9019-88c5294ed17e.jpg)

**Comment by cmoosman1** [comment]
@jtuckertw - This is resolved in the current build

**Comment by jtuckertw** [comment]
Fixed - Closed
