### ISSUE TITLE
Functionality : The Contact Us button as no functionality 

### ISSUE THREAD

**Issue by adamsisneros** [Tallwave/PIC-Subsalve#75]
Severity: Major
Location: Homepage
OS / OS Version: Global
Device / Browser: Global
 
Expected Results: 
  When the user clicks Contact Us, the site will redirect to the Contact Us page.
 
Actual Results: 
  When the user click Contact Us, the site doesn't react.
 
Steps To Reproduce: 
	1. Launch http://subsalve.wpengine.com/ on any supported platform
	2. Scroll down to Get in Touch section
	3. Click/Tap Contact Us
	4. Observe the site does not react
 
Notes: N/A

Rate of Reproduction: 100%
![ContactUs Button Issue](https://user-images.githubusercontent.com/10537386/66435031-20e06100-e9e1-11e9-8c8e-e9641f911aec.PNG)

**Comment by cmoosman1** [comment]
@jtuckertw - This is resolved in the current build
