### ISSUE TITLE
 Functionality : The Phone Number field on Contact Us page allows text to be submitted

### ISSUE THREAD

**Issue by adamsisneros** [Tallwave/PIC-Subsalve#76]
Severity: Minor
Location: Homepage
OS / OS Version: Global
Device / Browser: Global
 
Expected Results: 
  When the user types anything but numbers on the phone number field, the site will reject the number.
 
Actual Results: 
  The Phone number field allows for all text input without limits.
 
Steps To Reproduce: 
	1. Launch http://subsalve.wpengine.com/ on any supported device
	2. Scroll down to the Get in Touch section
	3. Fill the information
	4. Type random numbers and letters in the Phone field
	5. Click Submit
	6. Observe there is no warning
 
Notes: N/A

Rate of Reproduction: 100%
![Phone number Issue](https://user-images.githubusercontent.com/10537386/66435079-3c4b6c00-e9e1-11e9-85d6-c4ab2dbb85cb.PNG)

**Comment by cmoosman1** [comment]
@jtuckertw - This is resolved in the current build

**Comment by jtuckertw** [comment]
Fixed - Closed
