### ISSUE TITLE
Functionality : The See More button under Products jump to the top of the page

### ISSUE THREAD

**Issue by adamsisneros** [Tallwave/PIC-Subsalve#77]
Severity: Minor
Location: Homepage
OS / OS Version: Global
Device / Browser: Global
 
Expected Results: 
  When the user clicks the See More link, the site will redirect to the related product
 
Actual Results: 
  When the user clicks the See More link, the site jumps back to the top
 
Steps To Reproduce: 
	1. Launch http://subsalve.wpengine.com/ on any supported device
	2. Scroll down to the Accessories section
	3. Click/Tap See More
	4. Observe the site jumps up to the top of the site
 
Notes: N/A

Rate of Reproduction: 100%
![See More Issue](https://user-images.githubusercontent.com/10537386/66435115-55ecb380-e9e1-11e9-8a11-ddceb50de386.PNG)

**Comment by cmoosman1** [comment]
@jtuckertw - This is resolved in the current build
