### ISSUE TITLE
Text : The Title of some pages are incorrect on mobile

### ISSUE THREAD

**Issue by adamsisneros** [Tallwave/PIC-Subsalve#79]
Severity: Major
Location: Case Studies
OS / OS Version: Global Mobile
Device / Browser: Global Mobile
 
Expected Results: 
  When the user navigates the site, the site will keep consistency among all supported devices
 
Actual Results: 
  When the user navigates to the Case Studies page on mobile, the title says the page is Accessories
 
Steps To Reproduce: 
	1. Launch http://subsalve.wpengine.com/case-studies on any mobile supported device
	2. Observe the page titles are incorrect
 
Notes: 
	This also occurs on:http://subsalve.wpengine.com/news
	http://subsalve.wpengine.com/about-us
	http://subsalve.wpengine.com/products

Rate of Reproduction: 100%
![Mislabled Titled](https://user-images.githubusercontent.com/10537386/66435198-87fe1580-e9e1-11e9-91ad-17db8b60eb15.png)

**Comment by TheNewWallace** [comment]
@jtuckertw im not sure what they mean by this bug?

**Comment by jtuckertw** [comment]
@TheNewWallace The URL shows case studies but the page title shows Accessories, maybe?  I will need to dig deeper and check it out.  This is just a first glance assumption

**Comment by cmoosman1** [comment]
@jtuckertw - I believe this was content related Im not seeing it

**Comment by jtuckertw** [comment]
Duplicate - this is the issue with the bad navigations in certain contexts.  Closing and using more descriptive ticket.
