### ISSUE TITLE
Case Studies overview page:

### ISSUE THREAD

**Issue by jtuckertw** [Tallwave/PIC-Subsalve#8]
• Can we make sure these cards all stay the same height across? Right now they have varying lengths. I'm ok with putting a limit on the paragraph content  in order to make that happen.

• It looks like the "View Case Study" button text is off-center vertically.

• The cards also overlap at medium screen sizes

https://drive.google.com/file/d/18XcWljzU4JdYR33RoWJfkpFeEeuLhQUa/view?usp=sharing

https://drive.google.com/file/d/18e4wn4G-hCBjyy0sflmlCpoYV4zLvU77/view?usp=sharing

**Comment by cmoosman1** [comment]
@jtuckertw - This is resolved in the current build

**Comment by jtuckertw** [comment]
@jthiel - please revalidate and close if all looks good - thanks!
