### ISSUE TITLE
Visual : The first story in the case studies page has sizing issues on mobile

### ISSUE THREAD

**Issue by adamsisneros** [Tallwave/PIC-Subsalve#81]
Severity: Major
Location: Case Studies
OS / OS Version: Global Mobile
Device / Browser: Global Mobile
 
Expected Results: 
  When the user navigates the site on tablets, the site will scale correctly
 
Actual Results: 
  When the user navigates the homepage on iPad, the header text and button is broken or cut-off
 
Steps To Reproduce: 
	1. Launch http://subsalve.wpengine.com/  on iPad Air 2
	2. Observe the text and button is scaled incorrectly
 
Notes: N/A

Rate of Reproduction: 100%
![Case Studies Sizing](https://user-images.githubusercontent.com/10537386/66435282-bda2fe80-e9e1-11e9-8db1-fb959b08052b.png)

**Comment by cmoosman1** [comment]
@jtuckertw - This is resolved in the current build

**Comment by jtuckertw** [comment]
Text scales fine,, but the image is half sized in current build @cmoosman1

**Comment by cmoosman1** [comment]
@jtuckertw - This is resolved in the current build

**Comment by jtuckertw** [comment]
Resolved
