### ISSUE TITLE
Functionality : Hamburger menu does not appear on iPad 4th gen

### ISSUE THREAD

**Issue by adamsisneros** [Tallwave/PIC-Subsalve#82]
Severity: Critical
Location: Homepage
OS / OS Version: iOS 10.2.1
Device / Browser: iPad 4th gen
 
Expected Results: 
  When the user explores the site, all pages and links are as intended
 
Actual Results: 
  When the user navigate the site on iPad 4th gen
 
Steps To Reproduce: 
	1. Launch subsalve.wpengine.com on iPad 4th gen
	2. Observe the Hamburger menu is gone
 
Notes: N/A

Rate of Reproduction: 100%
![Hamburger Menu Issue](https://user-images.githubusercontent.com/10537386/66438056-c3501280-e9e8-11e9-8d6e-2963f6ce65bb.PNG)

**Comment by cmoosman1** [comment]
@jtuckertw - This is resolved in the current build

**Comment by jtuckertw** [comment]
Going on faith - closed.
