### ISSUE TITLE
Favicon in search bar

### ISSUE THREAD

**Issue by jtuckertw** [Tallwave/PIC-Subsalve#83]
Favicon of Subsalve's current logo is needed in searchbar

**Comment by cmoosman1** [comment]
@jtuckertw - This is resolved in the current build

**Comment by jtuckertw** [comment]
@cmoosman1  I'm not seeing this - will this only show in Production?

**Comment by cmoosman1** [comment]
@jtuckertw - Just want to make sure you guys are looking at the right URL http://subsalve.wpengine.com/?
<img width="1393" alt="Screen Shot 2019-10-14 at 6 38 39 PM" src="https://user-images.githubusercontent.com/49693121/66793382-00694880-eeb2-11e9-8e9b-7ceb87d4d5ea.png">

**Comment by jtuckertw** [comment]
D'oh!  Closing.
