### ISSUE TITLE
Homepage: Verbiage is illegible with the Ocean Tundra background image.

### ISSUE THREAD

**Issue by jtuckertw** [Tallwave/PIC-Subsalve#84]
Verbiage is illegible with the Ocean Tundra background image.  Suggest a new image?

![image](https://user-images.githubusercontent.com/45019034/66730316-bf1b5f00-ee05-11e9-9713-0767f27e4161.png)

**Comment by jthiel16** [comment]
@jtuckertw I'm not able to replicate this issue ... so it looks resolved to me. Ok if I close this?

**Comment by jtuckertw** [comment]
Hmm @jthiel16  every few days of QA, the Homepage  renders like this for me.  I'm concerned about closing it but we can close it until it reappears again.
