### ISSUE TITLE
Case Studies overview page (http://subsalve.wpengine.com/case-studies):

### ISSUE THREAD

**Issue by jtuckertw** [Tallwave/PIC-Subsalve#9]
In the "featured" case study, let's All-cap both the "FEATURED" AND "LOCATION" text, and add a gray bullet "•" after "FEATURED"

https://drive.google.com/file/d/18U281ELQqJ_kYECd4ve8QX3VfyZ_FzE1/view?usp=sharing

**Comment by cmoosman1** [comment]
@jtuckertw - This is resolved in the current build

**Comment by jtuckertw** [comment]
LGTM (Looks good to me) Please close if you are good with this.

**Comment by jthiel16** [comment]
Looks good, thank you
