### ISSUE TITLE
Homepage: Application Cards need brief descriptors instead of lorem ipsum (content)

### ISSUE THREAD

**Issue by jtuckertw** [Tallwave/PIC-Subsalve#90]
Product Cards need brief descriptors instead of lorem ipsum (content)

Per @TheNewWallace +jeff.tucker@tallwave.com this is a dev issue. they need to pull from the product page content i believe. +criss.moosman@tallwave.com please let me know if thats not the case

**Comment by jtuckertw** [comment]
@cmoosman1  Is it possible to use the descriptions that are on each of the Application pages within these cards?

**Comment by cmoosman1** [comment]
@jtuckertw - I added Kylie she isnt showing up so Im assigning this to you
