### ISSUE TITLE
Trade Show Event Calendar not loaded

### ISSUE THREAD

**Issue by jtuckertw** [Tallwave/PIC-Subsalve#92]
https://drive.google.com/open?id=0B6ZQMsMmAFJLQjRxRHRLSkU1YS1FZXJvVGJYWFpUdG5NOUNz

**Comment by jtuckertw** [comment]
@TheNewWallace Michael can you upload the events, please?

**Comment by TheNewWallace** [comment]
do we have news links to upload? i apologize i havent seen these

**Comment by britnigallello** [comment]
@jtuckertw let me know if these live somewhere.

**Comment by jtuckertw** [comment]
Thank you, @britnigallello 
Content Spreadsheet: https://docs.google.com/spreadsheets/d/1PzHKZ6jR9APVuwbpyVhKs4NxDefh8qjgErKj-IemT1Y/edit#gid=0

Tab 1/Subsalve Tradeshow schedule:
https://drive.google.com/open?id=0B6ZQMsMmAFJLQjRxRHRLSkU1YS1FZXJvVGJYWFpUdG5NOUNz

**Comment by kylielujan** [comment]
@victorjaquez this will be exactly the same as the one we did for AEF, except with the Subsalve tradeshows

**Comment by aguillen1** [comment]
@jtuckertw  I think I tagged you in the wrong task 🤦🏽‍♀️, but these events have been added. I deleted the May 12 and May 4 dates that are shown at the top of the list on the backend, but the omissions aren't being reflected here yet: http://subsalve.wpengine.com/

**Comment by jtuckertw** [comment]
@aguillen1 and @cmoosman1 Please Work together to see if there is something dev can do to fix the issue noted above.

**Comment by aguillen1** [comment]
This looks good on my end @jtuckertw http://subsalve.wpengine.com/

**Comment by jtuckertw** [comment]
Perfecto - thank you @aguillen1
