### ISSUE TITLE
Contact Us Form no longer allows input

### ISSUE THREAD

**Issue by jtuckertw** [Tallwave/PIC-Subsalve#93]
None of the fields are working.

The Address, Email and Phone are incorrect:
PHONE
(401) 884-8801

Email
sales@subsalve.com

Address
P.O. Box 2030
North Kingstown, RI 02852
USA

**Comment by cmoosman1** [comment]
@jtuckertw - This is resolved in the current build

**Comment by jtuckertw** [comment]
Email is still incorrect.
sales@subsalve.com

**Comment by cmoosman1** [comment]
@jtuckertw - This is resolved in the current build

**Comment by jtuckertw** [comment]
Perfect!
