### ISSUE TITLE
Footer: LinkedIn and Facebook links are not hooked up

### ISSUE THREAD

**Issue by jtuckertw** [Tallwave/PIC-Subsalve#95]

**Comment by cmoosman1** [comment]
@jtuckertw - This is resolved in the current build

**Comment by jtuckertw** [comment]
Retest Failed - Links lead back to homepage - not to FB or LinkedIn

**Comment by cmoosman1** [comment]
@jtuckertw - This is resolved in the current build

**Comment by jtuckertw** [comment]
Resolved
