### ISSUE TITLE
Applications is shown in the header menu - should it also be in the footer menu?

### ISSUE THREAD

**Issue by jtuckertw** [Tallwave/PIC-Subsalve#96]

**Comment by jthiel16** [comment]
@jtuckertw We left it out of the footer because there is no main "Applications" page. We would have to list out all of the individual pages if we wanted to go that direction.

I'm ok with it as is, leaving "Applications" out of the footer.

**Comment by jtuckertw** [comment]
perfecto - closed.  Thank you!
