### ISSUE TITLE
Products Page: Buoyancy Control System card text is misaligned

### ISSUE THREAD

**Issue by jtuckertw** [Tallwave/PIC-Subsalve#97]
http://subsalve.wpengine.com/products

Correctly sized Image is provided in comments below

![image](https://user-images.githubusercontent.com/45019034/73153051-81c69e80-408f-11ea-98fe-812b76864582.png)

**Comment by cmoosman1** [comment]
@jtuckertw - This is resolved in the current build

**Comment by cmoosman1** [comment]
@jtuckertw - This is resolved in the current build

**Comment by jtuckertw** [comment]
Still misaligned but should this card even be here?

If yes, it is not showing in the megamenu.  @jtuckertw to research with client

**Comment by jtuckertw** [comment]
Yes, this product needs to be added to the Products Menu within the Megamenu

**Comment by jtuckertw** [comment]
Tech specs doc - THere needs to be an image template that maintains the same height and width that the original spec was based on.  In this particular case we need 150x150 images.  

We need to create a 150x150 image for BCS.  Currently it is 150x99

**Comment by jtuckertw** [comment]
@jthiel16 Jason: I'd love to get this one closed without going to the client.  Is there any quick magic that you can work that makes this 150x99 image into a 150x150?  Please let me know.  Thanks!

**Comment by jthiel16** [comment]
Hey @jtuckertw, yeah that's no problem. Here is the 150x150 image:
[https://drive.google.com/file/d/1gIUIg5ORzbqDg297x9L-hUUc7n-4bblq/view?usp=sharing](url)

I took a look in WP and didn't see a spot to make the image swap

**Comment by jtuckertw** [comment]
Please replace existing image with new one provided by Jason

**Comment by kylielujan** [comment]
@jtuckertw done and ready for QA

**Comment by jtuckertw** [comment]
Title Text is still not at same height as other products in the row.

**Comment by aguillen1** [comment]
@jtuckertw Alignment Issue has been resolved: http://subsalve.wpengine.com/products

**Comment by jtuckertw** [comment]
FIXED
