### ISSUE TITLE
Products Page: Some Products have weird symbols in them (dev)

### ISSUE THREAD

**Issue by jtuckertw** [Tallwave/PIC-Subsalve#98]
- [ ] Enclosed Shallow Water Flotation Bags has weird symbol in it (dev)
- [ ] Professional Enclosed Lift Bags has weird symbol in it. (dev)
- [ ] Vehicle Recovery Systems has weird symbol in it (dev)

![image](https://user-images.githubusercontent.com/45019034/66731312-a01fcb80-ee0b-11e9-895f-341f53b122bb.png)

**Comment by cmoosman1** [comment]
@jtuckertw - This is resolved in the current build

**Comment by jtuckertw** [comment]
Still out there - used incognito view (Chrome)

**Comment by cmoosman1** [comment]
@jtuckertw - This is resolved in the current build

**Comment by jtuckertw** [comment]
Desktop/Chrome/ Version 78.0.3904.108 (Official Build) (64-bit)
Tested and found on Hard refresh in incognito mode.

**Comment by jtuckertw** [comment]
Not Fixed

**Comment by jtuckertw** [comment]
Fixed!
